import fs from 'node:fs';import crypto from 'node:crypto';
export function importMariage(final,original,key){
 const rows=JSON.parse(fs.readFileSync('research/japanese-index.json')).filter(x=>x.series==='mariage').sort((a,b)=>a.volume-b.volume);const names=new Map(fs.readFileSync('research/mariage-names.tsv','utf8').trim().split('\n').map(l=>{const [idx,name,producer]=l.split('\t');return [idx,{name,producer}]}));
 const regions=JSON.parse(fs.readFileSync('research/region-centroids.json'));const byKey=new Map();for(const n of final){byKey.set(n.mangaKey,n);byKey.set(key(n.en,n.producer),n);}const existing=new Map(original.map(n=>[key(n.en,n.producer),n]));let joined=0,added=0,excluded=[];const seen=new Set();
 for(const v of rows)for(let i=0;i<v.rows.length;i++){const r=v.rows[i],idx=v.volume+':'+i,t=names.get(idx);if(!t)throw Error('Missing sequel translation '+idx);if(t.name==='EXCLUDE SAKE'){excluded.push({...r,reason:'日本清酒，非葡萄酒'});continue;}const k=key(t.name,t.producer);let n=byKey.get(k);
 if(!n){const old=existing.get(k);n=old?{...old,producer:t.producer}:{id:'manga-'+crypto.createHash('sha256').update(k).digest('hex').slice(0,12),name:t.name,en:t.name,producer:t.producer,type:/泡/.test(r.typeJa||'')?'起泡酒':/ロゼ/.test(r.typeJa||'')?'桃红葡萄酒':/白/.test(r.typeJa||'')?'白葡萄酒':'红葡萄酒',lat:null,lng:null,place:'产地待核验',geoPrecision:'待定位'};n.manga=[];n.mangaKey=k;n.reviewStatus='secondary-index';n.japaneseNames=[];if(old)n.geoPrecision='既有地图关联点';final.push(n);byKey.set(k,n);added++;}else if(!seen.has(n.id))joined++;seen.add(n.id);
 n.japaneseNames=[...new Set([...(n.japaneseNames||[]),r.nameJa])];let vintage=r.vintage;if(!vintage&&/N\.?V\.?/i.test(r.titleJa.normalize('NFKC')))vintage='NV';const a={series:'mariage',volume:v.volume,vintage,source:r.source,status:'secondary-index',sourceNameJa:r.nameJa,sourceProducerJa:r.producerJa};if(idx==='16:11')a.conflict='日文酒单列2014，尚待核验漫画原页与年份。';if(!n.manga.some(x=>x.series===a.series&&x.volume===a.volume&&x.vintage===a.vintage))n.manga.push(a);
 let region=r.regionJa||'';if(['1:6'].includes(idx))region='フランス　ロワール';if(['1:7'].includes(idx))region='フランス　ボルドー';if(idx==='5:0')region='';if(idx==='21:5')region='';
 if(n.lat==null){const g=regions.find(g=>region.includes(g.match));if(g)Object.assign(n,{lat:g.lat,lng:g.lng,place:g.place,geoSource:r.source,geoPrecision:'大产区示意点 · 最终章二手酒单产地，待生产者复核'});}
 }
 const result={volumes:26,sourceOccurrences:rows.reduce((s,v)=>s+v.rows.length,0),wineOccurrences:266,uniqueWines:seen.size,newCatalogEntries:added,joinedExisting:joined,excluded,scope:'最终章26卷 · 单一公开酒单索引，未完成原页核验'};fs.writeFileSync('research/mariage-status.json',JSON.stringify(result,null,2));return result;
}
