const fs=require('fs'),path=require('path');
const g=JSON.parse(fs.readFileSync('research/france-expansion/generated.json'));
const manifest=JSON.parse(fs.readFileSync(fs.existsSync('../france-assets/manifest.json')?'../france-assets/manifest.json':'research/france-expansion/asset-manifest.json'));
const photos={},labels={};
const photoMap={'figeac.jpg':['figeac','飞卓酒庄建筑与秋季葡萄园'],'pavie-verified.jpg':['pavie','柏菲酒庄酿造室内的木制发酵罐'],'mission-appellation.jpg':['la-mission-haut-brion','美讯酒庄建筑、回廊与葡萄园'],'yquem-estate.jpeg':['d-yquem','滴金酒庄城堡、花园与葡萄园'],'roederer-large.jpg':['louis-roederer','路易王妃位于兰斯的总部庭院'],'trimbach.jpg':['trimbach','婷芭克酒庄建筑及背后的葡萄园'],'zind.jpg':['zind-humbrecht','辛特-洪布列希特酒窖内的大木桶']};
for(const m of manifest){const base=path.basename(m.localFile),p=photoMap[base];if(p){const dest='estates/france-'+base.replace('.jpeg','.jpg');if(fs.existsSync(m.localFile))fs.copyFileSync(m.localFile,'web/'+dest);else if(!fs.existsSync('web/'+dest))throw Error('Missing verified asset '+dest);photos[p[0]]=[{src:dest,caption:p[1],source:m.sourcePage,credit:m.credit,width:m.dimensions[0],height:m.dimensions[1]}];}const wineId={'figeac-label.png':'figeac-grand','pavie-label.jpg':'manga-97e422499ed3','mission-label.jpg':'manga-8b04528e0d14'}[base];if(wineId){const dest='labels/france-'+base;if(fs.existsSync(m.localFile))fs.copyFileSync(m.localFile,'web/'+dest);else if(!fs.existsSync('web/'+dest))throw Error('Missing verified asset '+dest);labels[wineId]={src:dest,wine:m.name,kind:'label',sourcePage:m.sourcePage,sourceCredit:m.credit,imageUrl:m.imageURL,visibleVintage:null,displayNote:'历史酒标图，图中未标年份；分级文字反映酒标时期，不代表今天的分级。',resolutionNote:'原图尺寸有限'};}}
fs.writeFileSync('research/france-expansion/asset-manifest.json',JSON.stringify(manifest.filter(m=>photoMap[path.basename(m.localFile)]||/figeac-label|pavie-label|mission-label/.test(m.localFile)),null,2));
const aliases={'figeac':['飞卓','菲雅克'],'pavie':['柏菲'],'d-yquem':['滴金','伊甘'],'louis-roederer':['路易王妃'],'trimbach':['婷芭克'],'hugel':['雨果'],'la-mission-haut-brion':['美讯'],'la-conseillante':['康赛扬'],'l-evangile':['乐王吉'],'louis-jadot':['路易亚都'],'joseph-drouhin':['约瑟夫杜鲁安'],'leflaive':['勒弗莱'],'francois-raveneau':['拉芙诺']};
// Share repeated field values without changing any record or HTTP content encoding.
const defaults={wine:{},estate:{}};for(const [type,predicate]of [['wine',n=>n.kind==='wine'],['estate',n=>n.producer]]){const rows=g.nodes.filter(predicate);for(const key of Object.keys(rows[0]||{})){if(['id','name','en','parent','producerId','appellationId'].includes(key))continue;const values=new Map();for(const row of rows){const value=JSON.stringify(row[key]);if(value!==undefined)values.set(value,(values.get(value)||0)+1);}const top=[...values].sort((a,b)=>b[1]-a[1])[0];if(top&&top[1]>rows.length*.6)defaults[type][key]=JSON.parse(top[0]);}}
const packed={sources:g.sources,updates:g.updates,profiles:g.profiles,nodes:g.nodes.map(n=>{const result={...n},d=defaults[n.kind==='wine'?'wine':'estate'];if(n.kind==='wine'||n.producer){result._defaults=n.kind==='wine'?'wine':'estate';for(const [k,v]of Object.entries(d))if(JSON.stringify(n[k])===JSON.stringify(v))delete result[k];}return result;})};
fs.writeFileSync('web/france-expansion.js',`// Official directory snapshots researched 2026-09-30; never a claim of all French estates.\n(()=>{\nconst data=${JSON.stringify(packed)};\nObject.assign(SOURCES,data.sources);\nfor(const [id,patch]of Object.entries(data.updates)){const n=NODES.find(n=>n.id===id);if(n)Object.assign(n,patch);}\nconst defaults=${JSON.stringify(defaults)};for(const n of data.nodes){const kind=n._defaults;delete n._defaults;NODES.push(kind?Object.assign({},defaults[kind],n):n);}\nObject.assign(ESTATE_PROFILES,data.profiles);Object.assign(ESTATE_PHOTOS,${JSON.stringify(photos)});Object.assign(WINE_IMAGES,${JSON.stringify(labels)});\nconst aliases=${JSON.stringify(aliases)};for(const [id,names]of Object.entries(aliases)){const e=NODES.find(n=>n.id===id);if(e)e.aliases=names;}\nfor(const m of MANGA_WINES){const w=NODES.find(n=>n.id===m.id&&n.kind==='wine');if(!w)continue;m.placeId=w.appellationId||NODES.find(e=>e.id===w.producerId)?.parent;m.lat=w.lat;m.lng=w.lng;m.geoPrecision='关联产区示意点；非酒庄精确定位';}\nMANGA_STATS.existingMatches=MANGA_WINES.filter(m=>NODES.some(n=>n.id===m.id&&n.kind==='wine')).length;MANGA_STATS.mapped=MANGA_WINES.filter(m=>m.lat!=null&&m.lng!=null).length;MANGA_STATS.pendingLocations=MANGA_WINES.length-MANGA_STATS.mapped;\n})();\n`);
