// Official estate and wine range, checked 2026-09-30. No manga attribution without a verified record.
Object.assign(SOURCES,{
 'angelus-estate':['Château Angélus · 酒庄与家族历史','https://www.angelus.com/en/the-property.html'],
 'angelus-wines':['Château Angélus · 官方酒款系列','https://www.angelus.com/en/the-wines.html'],
 'angelus-2012':['Angélus · 2012 历史分级','https://www.angelus.com/en/le-premier.html'],
 'angelus-2022':['Angélus · 退出 2022 分级声明','https://www.angelus.com/en/412-saint-emilion-2022-classification.html'],
 'angelus-tempo':['Tempo d’Angélus · 葡萄园与酿造','https://tempo-angelus.com/en/homepage/']
});
(()=>{
 const classification='Saint-Émilion Grand Cru AOC；2012 年获 Premier Grand Cru Classé A，已退出 2022 分级，不标作现行 A 级。';
 const base={lat:44.893,lng:-0.1715,zoom:16,source:['angelus-estate','angelus-wines'],grapes:'梅洛 · 品丽珠；具体比例随酒款与年份变化',soil:'圣埃美隆坡地；不同酒款选用的地块并不相同',climate:'波尔多海洋性气候；具体年份的降雨与温度影响成熟。',locationNote:'按酒庄官网交通链接定位至庄园附近；不是葡萄园边界。'};
 NODES.push({...base,id:'angelus',parent:'saintemilion',name:'金钟酒庄',en:'Château Angélus',producer:true,estate:true,national:true,mapLocated:true,tier:classification,classificationNote:classification,classificationGroup:'历史 A 级 · 不在 2022 分级内',summary:'de Boüard de Laforest 家族经营的圣埃美隆酒庄，以钟为标志；旗下酒款覆盖 Saint-Émilion Grand Cru、Saint-Émilion 与 Bordeaux 法定产地。',source:[...base.source,'angelus-2012','angelus-2022']});
 const rows=[
 {id:'angelus-grand',name:'金钟正牌',en:'Château Angélus',parent:'saintemilion',tier:'正牌酒',labelText:'Château Angélus · Saint-Émilion Grand Cru AOC',summary:'金钟酒庄的主牌酒，梅洛与品丽珠共同构成其身份；调配因年份而异。',labelLesson:classification+' 酒标上的钟是酒庄标志；历史酒标保留当年的分级用语。',source:['angelus-estate','angelus-wines','angelus-2012','angelus-2022']},
 {id:'angelus-carillon',name:'金钟副牌 · Carillon',en:'Carillon d’Angélus',parent:'saintemilion',tier:'副牌酒 · Carillon',labelText:'Carillon d’Angélus · Saint-Émilion Grand Cru AOC',summary:'首个年份为 1987。来自不同圣埃美隆地块，拥有独立风格。',grapes:'梅洛 · 品丽珠 · 赤霞珠；比例随年份变化',labelLesson:'Saint-Émilion Grand Cru 是法定产地名称；副牌酒不继承正牌酒的历史 A 级酒庄分级。'},
 {id:'angelus-no3',name:'金钟三号 · N°3',en:'N°3 d’Angélus',parent:'saintemilion',tier:'第三款酒 · N°3',labelText:'N°3 d’Angélus · Saint-Émilion AOC',summary:'以梅洛为主，强调年轻时的易饮性；较短陈酿，不使用新橡木桶。',grapes:'梅洛为主；官网系列介绍约 85–90%，具体年份以技术表为准',labelLesson:'官网列为 Saint-Émilion，并非 Saint-Émilion Grand Cru。N°3 是酒款名称，不是法定等级。'},
 {id:'angelus-tempo',name:'金钟韵律 · Tempo',en:'Tempo d’Angélus',parent:'bordeaux',tier:'其他酒款 · Tempo',labelText:'Tempo d’Angélus · Bordeaux AOC',summary:'2019 年创立，面向较早饮用。葡萄来自 Castillon 与 Francs 一带的自有葡萄园。',grapes:'具体品种比例以相应年份技术表为准',soil:'黏土石灰岩坡地，含凝灰岩与泥灰岩。',source:['angelus-wines','angelus-tempo'],labelLesson:'葡萄园分布于 Castillon-la-Bataille、Saint-Magne-de-Castillon、Sainte-Colombe 与 Francs 一带，在 Chai Carillon 专用空间酿造。酒标法定名称为 Bordeaux AOC，不因酒庄位于圣埃美隆而改写。地图定位为生产者关联地点，并非本款葡萄园位置。'}
 ];
 for(const row of rows)NODES.push({...base,kind:'wine',producerId:'angelus',lesson:row.labelLesson,...row});
})();

Object.assign(WINE_IMAGES,{"angelus-grand": {"wine": "Château Angélus", "wineName": "Château Angélus", "src": "labels/angelus-grand.png", "sourcePage": "https://www.angelus.com/en/the-wines.html", "imageUrl": "https://www.angelus.com/en/img/03-Bouteille-angelus.png", "sourceCredit": "Château Angélus 官网", "visibleVintage": "2015", "kind": "label-crop", "displayNote": "图片为 2015 年份，切换收藏年份不会改变酒标图片。", "crop": {"x": 6, "y": 904, "width": 565, "height": 818, "imageWidth": 579, "imageHeight": 2148}}, "angelus-carillon": {"wine": "Carillon d’Angélus", "wineName": "Carillon d’Angélus", "src": "labels/angelus-carillon.jpg", "sourcePage": "https://www.bordeaux-tradition.com/wp-content/uploads/2018/02/carillon-d-angelus-2019-ang.pdf", "imageUrl": "https://www.bordeaux-tradition.com/wp-content/uploads/2018/02/carillon-d-angelus-2019-ang.pdf", "sourceCredit": "Bordeaux Tradition 技术资料", "visibleVintage": "2015", "kind": "label", "displayNote": "图片为 2015 年份，切换收藏年份不会改变酒标图片。"}, "angelus-no3": {"wine": "N°3 d’Angélus", "wineName": "N°3 d’Angélus", "src": "labels/angelus-no3.png", "sourcePage": "https://www.angelus.com/en/the-wines.html", "imageUrl": "https://www.angelus.com/en/img/03-bis-bt-number3.png", "sourceCredit": "Château Angélus 官网", "visibleVintage": "2018", "kind": "label-crop", "displayNote": "图片为 2018 年份，切换收藏年份不会改变酒标图片。", "crop": {"x": 5, "y": 924, "width": 532, "height": 750, "imageWidth": 548, "imageHeight": 2199}}, "angelus-tempo": {"wine": "Tempo d’Angélus", "wineName": "Tempo d’Angélus", "src": "labels/angelus-tempo.png", "sourcePage": "https://www.angelus.com/en/the-wines.html", "imageUrl": "https://www.angelus.com/en/img/BouteilleTEMPO-solo.png", "sourceCredit": "Château Angélus 官网", "visibleVintage": "2019", "kind": "label-crop", "displayNote": "图片为 2019 年份，切换收藏年份不会改变酒标图片。", "crop": {"x": 18, "y": 960, "width": 501, "height": 662, "imageWidth": 540, "imageHeight": 2188}}});
