'use strict';
const $=s=>document.querySelector(s), BY_ID=Object.fromEntries(NODES.map(n=>[n.id,n]));
const children=id=>NODES.filter(n=>n.parent===id);
function ancestors(n){const a=[];while(n){a.unshift(n);n=BY_ID[n.parent]}return a}
function region(n){return ancestors(BY_ID[n.appellationId]||n).find(x=>x.parent==='france')}
function depth(n){return ancestors(n).length-1}
const initialWineRoute=location.hash;
const state={id:'france',tab:'earth',year:2022,labels:true,grade:'all',query:''};
const map=L.map('map',{zoomControl:false,minZoom:4,maxZoom:17,scrollWheelZoom:true,maxBounds:[[32,-20],[60,23]],maxBoundsViscosity:.6});
L.control.zoom({position:'topright'}).addTo(map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
map.createPane('geography');map.getPane('geography').style.zIndex='190';
fetch('europe.json?v=identity-v2').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>L.geoJSON(d,{pane:'geography',interactive:false,style:f=>({color:'#aebbaa',weight:1,fillColor:f.properties.name==='France'?'#f2f1e4':'#e4e8dc',fillOpacity:1})}).addTo(map)).catch(()=>{$('#tile-note').hidden=false});
const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · Natural Earth',opacity:.69});
let streetMapStarted=false;function startStreetMap(){if(streetMapStarted)return;streetMapStarted=true;tiles.addTo(map)}
map.once('dragstart',startStreetMap);map.once('zoomstart',e=>{if(e.originalEvent)startStreetMap()});$('#map').addEventListener('wheel',startStreetMap,{once:true,passive:true});$('#map').addEventListener('click',startStreetMap,{once:true});
let loadedTiles=0;tiles.on('tileload',()=>{loadedTiles++;$('#tile-note').hidden=true});tiles.on('tileerror',()=>{if(!loadedTiles)$('#tile-note').hidden=false});
const markers=L.layerGroup().addTo(map);
function escapeHTML(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mapChildren(id){return children(id).filter(n=>n.mapLocated!==false).filter(n=>!(n.producer&&region(n)?.id==='burgundy'))}
function frontier(id,z){return mapChildren(id).flatMap(n=>mapChildren(n.id).length&&z>=n.zoom-.25?frontier(n.id,z):[n])}
function relatedWines(n){return NODES.filter(w=>w.kind==='wine'&&(w.id===n.id||w.producerId===n.id||ancestors(w).some(a=>a.id===n.id)||w.appellationId===n.id||w.appellationId&&ancestors(BY_ID[w.appellationId]).some(a=>a.id===n.id)))}
function isVillage(n){return n.directory||['aoc','igp'].includes(n.kind)||!n.producer&&!n.kind&&depth(n)===3}
function allowMapImage(n){return state.labels&&map.getZoom()>=14&&!isVillage(BY_ID[state.id])&&!isVillage(n)}
function imageFor(n){if(n.producer)return null;if(WINE_IMAGES[n.id])return {wine:n,img:WINE_IMAGES[n.id]};const w=relatedWines(n).find(w=>WINE_IMAGES[w.id]);return w?{wine:w,img:WINE_IMAGES[w.id]}:null}
function labelImage(img,alt,cls=''){
 if(!img.crop)return `<img class="label-visual ${cls}" src="${img.src}" alt="${escapeHTML(alt)}" loading="lazy" draggable="false">`;
 const c=img.crop,clip='label-crop-'+img.src.replace(/[^a-z0-9]/gi,'-');return `<svg class="label-visual ${cls}" viewBox="${c.x} ${c.y} ${c.width} ${c.height}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${escapeHTML(alt)}" style="overflow:hidden"><defs><clipPath id="${clip}" clipPathUnits="userSpaceOnUse"><rect x="${c.x}" y="${c.y}" width="${c.width}" height="${c.height}"/></clipPath></defs><image clip-path="url(#${clip})" href="${img.src}" x="0" y="0" width="${c.imageWidth}" height="${c.imageHeight}"/></svg>`;
}
function imageCaption(img){return img.visibleVintage?`图示 ${img.visibleVintage} 年酒标`:'酒标图片 · 未确认年份'}
function mapCoverage(n){const es=appellationEstates(n),ws=relatedWines(n);return {estates:es.length,located:es.filter(e=>e.mapLocated!==false).length,wines:ws.length,labels:ws.filter(w=>WINE_IMAGES[w.id]).length};}
function mapDisplayNodes(selected,z){
 if(selected.kind==='wine')return selected.mapLocated===false?[]:[selected];
 if(selected.producer){const ws=relatedWines(selected).filter(w=>w.mapLocated!==false&&(!state.mangaOnly||MANGA_BY_ID[w.id]));return ws.length?ws:selected.mapLocated===false?[]:[selected];}
 if(selected.id!=='france'&&(selected.directory||depth(selected)>=2)){const es=appellationEstates(selected).filter(e=>e.mapLocated!==false&&(!state.mangaOnly||relatedWines(e).some(w=>MANGA_BY_ID[w.id])));if(es.length)return es;}
 return frontier('france',z);
}
function renderMarkers(){
 const selected=BY_ID[state.id],selectedPic=imageFor(selected),floating=state.labels&&(selected.estate||selected.kind==='wine')&&selected.mapLocated===false&&selectedPic;$('#selected-label').hidden=!floating;if(floating)$('#selected-label').innerHTML=`<button data-label="${selectedPic.wine.id}" aria-label="放大酒标">${labelImage(selectedPic.img,selectedPic.wine.en+"酒标")}</button><b>${escapeHTML(selected.name)}</b><small>${imageCaption(selectedPic.img)}</small><small>关联本产区 · 酒庄点位待核实</small>`;
 const village=BY_ID[state.id],meta=DIRECTORY_META[village.id];$('#village-summary').hidden=!meta;if(meta){const estates=directoryEstates(village.id),rankCounts=[1,2,3,4,5].map(r=>estates.filter(e=>e.rank===r).length);$('#village-summary').innerHTML=`<b>${escapeHTML(village.en.toUpperCase())} · ${escapeHTML(village.name)}</b><div><strong>${meta.total}</strong> 家酒庄 <span>本图收录 ${estates.length} 家</span></div><small>列级庄 ${estates.filter(e=>e.rank).length}：一级 ${rankCounts[0]} · 二级 ${rankCounts[1]} · 三级 ${rankCounts[2]} · 四级 ${rankCounts[3]} · 五级 ${rankCounts[4]}</small><small>Cru Bourgeois 2025：${estates.filter(e=>e.cb2025).length} 家 · 村庄层级仅显示数量</small>`;}
 if(village.nationalDirectory){const es=appellationEstates(village);$('#village-summary').hidden=false;$('#village-summary').innerHTML=`<b>${escapeHTML(village.en)}</b><div><strong>${es.length}</strong> 家已收录生产者 <span>${relatedWines(village).length} 款关联酒</span></div><small>已定位 ${mapCoverage(village).located} / ${es.length} 家 · 酒标 ${mapCoverage(village).labels} / ${relatedWines(village).length} 款</small><small>点击地图点进入酒庄，再查看旗下酒款与酒标</small>`;}
 markers.clearLayers();const z=map.getZoom(),ns=mapDisplayNodes(selected,z),groups=new Map(),cardBoxes=[];
 for(const n of ns){const pt=map.latLngToContainerPoint([n.lat,n.lng]);const key=n.producer?`estate:${Math.floor(pt.x/50)},${Math.floor(pt.y/50)}`:n.kind==='wine'?`${n.lat},${n.lng}`:n.id;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(n)}
 for(const group of groups.values()){
  const n=group[0];if(group.length>1&&group.every(e=>e.producer)){const lat=group.reduce((s,e)=>s+e.lat,0)/group.length,lng=group.reduce((s,e)=>s+e.lng,0)/group.length;L.marker([lat,lng],{icon:L.divIcon({className:'atlas-marker',html:`<button class="estate-cluster" aria-label="展开 ${group.length} 家酒庄"><b>${group.length}</b><span>酒庄</span></button>`,iconSize:[48,48],iconAnchor:[24,24]}),title:group.map(e=>e.name).join(' · ')}).on('click',()=>{if(map.getZoom()<17){map.fitBounds(group.map(e=>[e.lat,e.lng]),{padding:[55,55],maxZoom:17});}else{$('#content').innerHTML=`<button class="text-button" data-place="${state.id}">返回当前产地</button><h2>此处的 ${group.length} 家酒庄</h2>${group.map(card).join('')}`;}}).addTo(markers);continue;}let shown=group.some(a=>allowMapImage(a)&&imageFor(a));const pt=map.latLngToContainerPoint([n.lat,n.lng]),width=group.length>1?244:126,rect={x:pt.x-width/2,y:pt.y-118,w:width,h:118};if(shown&&cardBoxes.some(b=>rect.x<b.x+b.w+12&&rect.x+rect.w+12>b.x&&rect.y<b.y+b.h+12&&rect.y+rect.h+12>b.y))shown=false;if(shown)cardBoxes.push(rect);let html;
  if(shown){html=`<div class="map-label-card ${group.length>1?'paired':''}">${group.map(a=>{const pic=imageFor(a);return `<button class="map-label-choice" data-place="${a.id}" aria-label="探索 ${escapeHTML(a.name)}">${pic?`${labelImage(pic.img,pic.img.wine+"真实酒标")}`:''}<b>${escapeHTML(a.name)}</b><small>${a.kind==='wine'?(pic?imageCaption(pic.img):a.tier):`${relatedWines(a).filter(w=>WINE_IMAGES[w.id]).length} 张关联酒标`}</small></button>`}).join('')}<span class="label-anchor"></span></div>`}
  else if(isVillage(n))html=`<div class="village-pin"><b>${escapeHTML(n.name)}</b><small>${DIRECTORY_META[n.id]?`${DIRECTORY_META[n.id].total} 家酒庄 · ${directoryEstates(n.id).filter(e=>e.rank).length} 家列级庄`:`${appellationEstates(n).length} 家已收录生产者`}</small></div>`;
  else html=`<div class="pin ${n.overview?'overview':''} ${n.kind==='climat'?'climat-pin':''} ${n.producer?'leaf':''} ${state.id===n.id?'selected':''}"><span class="pin-dot"></span><span class="pin-label">${escapeHTML(n.name)}${typeof mangaBadge==='function'?mangaBadge(n.id):''}${z<16?`<small>${escapeHTML(n.tier||n.en)}</small>`:''}</span></div>`;
  const icon=L.divIcon({className:'atlas-marker',html,iconSize:[20,20],iconAnchor:[0,0]});L.marker([n.lat,n.lng],{icon,title:n.name,alt:`探索${n.name}`,keyboard:true}).on('click',e=>{const b=e.originalEvent?.target?.closest('[data-place]');select(b?.dataset.place||n.id)}).addTo(markers)
 }
 const d=z<8?1:z<11?2:z<14?3:z<16?4:z<17?5:6;
 $('#level').textContent=['','01 / 大产区','02 / 子产区','03 / 村庄与 AOC','04 / 园地与酒庄','05 / 具名园地与酒款','06 / 酒款与年份'][d];document.querySelectorAll('.level-dots i').forEach((el,i)=>el.classList.toggle('on',i<d));
}
map.on('zoomend',renderMarkers);map.on('moveend',renderMarkers);
function sourceHTML(keys){const k=[...new Set(keys)].filter(k=>SOURCES[k]);return k.length?`<details class="sources"><summary>资料来源与统计依据</summary>${k.map(k=>`<a href="${escapeHTML(SOURCES[k][1])}" target="_blank" rel="noopener noreferrer">${escapeHTML(SOURCES[k][0])} ↗</a>`).join('')}<p>学习摘要；并非酒款评分或全量数据库。</p></details>`:''}
function card(n){const label=n.tier||(n.deep?'深度探索':n.overview?'产区概览':n.producer?'生产者':depth(n)===3?'村庄 / AOC':'子产区');const img=n.producer?null:WINE_IMAGES[n.id];return `<button class="location ${img?'with-thumb':''}" data-place="${n.id}">${img?`${labelImage(img,img.wine+"真实酒标")}`:''}<span class="card-copy"><span class="loc-head"><b>${n.name}</b><em>${label}</em></span><small>${n.en}</small>${n.producer?`<span class="label-coverage">${NODES.filter(w=>w.kind==='wine'&&w.producerId===n.id).length} 款酒已收录</span>`:''}${n.parent==='france'?`<p>${n.grapes}</p>`:''}</span></button>`}
function classification(n){const note=ancestors(n).reverse().find(a=>a.classificationNote)?.classificationNote;if(note)return `<details class="classification" open><summary>怎样读这里的产地与分级</summary><p>${escapeHTML(note)}</p></details>`;const r=region(n);if(!r||!['bordeaux','burgundy'].includes(r.id))return '';return `<details class="classification" ${['burgundy','vosne','gevrey','pommard','bordeaux'].includes(n.id)?'open':''}><summary>按酒标理解层级 · ${r.name}</summary>${r.id==='burgundy'?`<div class="tier-flow"><span>大区 AOC</span><span>村庄 AOC</span><span>村庄＋Premier Cru＋园名</span><span>Grand Cru 独立 AOC</span></div><p>上列为酒标类型。地图中的村庄按地理位置组织；一级园与特级园是并列分支，不是递进的上下级。子产区（如夜丘）也不自动成为该酒款的酒标 AOC。</p>`:`<div class="tier-flow"><span>产区 AOC</span><span>酒庄／生产者</span><span>正牌、副牌等具体酒款</span><span>年份</span></div><p>酒庄分级是独立属性，正副牌是酒款关系，均不代表缩小一层法定地理范围。</p>`}</details>`}
function labelPanel(n){const img=WINE_IMAGES[n.id];return img?`<figure class="label-feature"><button data-label="${n.id}" aria-label="放大真实酒标">${labelImage(img,img.wine+"酒标")}</button><figcaption>${imageCaption(img)} · 点击放大</figcaption></figure><p class="image-year-note">${img.visibleVintage&&Number(img.visibleVintage)!==state.year?`当前年份背景：${state.year}；此图仍为 ${img.visibleVintage}，不代表所选年份的实物。`:!img.visibleVintage?'图片中未能确认年份，不代表这款酒是无年份酒。':'图示年份与当前年份背景相同。'}${n.id==='cheval-grand'?' 图上酒庄分级文字反映历史版本，不代表现行状态。':''}</p>`:''}
function winePanel(n){const prod=BY_ID[n.producerId],img=WINE_IMAGES[n.id];return `${labelPanel(n)}${img?.displayNote?`<p class="smallnote">${escapeHTML(img.displayNote)}</p>`:''}<span class="eyebrow">READ THE LABEL</span><h2>把一张酒标读成四条线索</h2><dl><div class="fact"><dt>产地与法定名称</dt><dd>${n.labelText}${n.appellationId&&BY_ID[n.appellationId]?`<br><button class="text-button" data-place="${n.appellationId}">查看 ${escapeHTML(BY_ID[n.appellationId].name)} 产地</button>`:''}</dd></div><div class="fact"><dt>生产者</dt><dd><button class="text-button" data-place="${prod.id}">${prod.en}</button></dd></div><div class="fact"><dt>酒款与标示等级</dt><dd>${n.tier} · ${n.en}</dd></div><div class="fact"><dt>年份背景</dt><dd><button class="text-button" data-tab-action="sky">${state.year} · 查看${region(n).name}年份</button></dd></div></dl>${lesson(n.labelLesson)}${!img?'<p class="smallnote">本酒款暂未收录真实酒标图。</p>':''}${sourceHTML(n.source)}${img?`<div class="image-credit">图片：<a href="${img.sourcePage}" target="_blank" rel="noopener">${img.sourceCredit}</a>。原图版权归其权利人。</div>`:''}`}
function lesson(text){return `<div class="lesson"><strong>带着一个问题去品尝</strong><p>${text}</p></div>`}
function facts(n){return `<dl><div class="fact"><dt>葡萄品种 / GRAPES</dt><dd>${n.grapes}</dd></div><div class="fact"><dt>土壤与地形 / SOIL</dt><dd>${n.soil}</dd></div><div class="fact"><dt>长期气候 / CLIMATE</dt><dd>${n.climate}</dd></div></dl>`}
function earth(n){if(n.directory)return directoryPanel(n);if(n.kind==='wine')return winePanel(n);const raw=mapChildren(n.id);const cs=[...new Map([...raw.map(x=>x.kind==='wine'?(BY_ID[x.producerId]||x):x),...NODES.filter(w=>w.kind==='wine'&&w.appellationId===n.id).map(w=>BY_ID[w.producerId]).filter(Boolean)].map(x=>[x.id,x])).values()];if(n.id==='france')return `<div class="section-head"><b>选择你的第一站</b><small>${children('france').length} 个地区 · 全国扩展中</small></div>${cs.map(card).join('')}${lesson(n.lesson)}<p class="smallnote">${NODES.filter(e=>e.producer).length} 家生产者 · ${NODES.filter(e=>e.kind==='wine').length} 款酒已收录。当前为法国主要葡萄酒产区的学习名录，尚非全国全量数据库。</p>`;return `${classification(n)}${n.labelText?`<div class="label-reading"><span>酒标上可见的产地表达</span><b>${n.labelText}</b><p>${n.relationNote||''}</p></div>`:''}${n.estate?estateDetail(n)+estateLabels(n):''}${facts(n)}${cs.length?`<div class="section-head"><b>${n.parent==='france'?'深入子产区':cs[0].kind==='wine'?'关联酒款':n.id==='vosne'||n.id==='gevrey'||n.id==='pommard'?'按园名与等级继续下探':cs[0].producer?'在这里认识生产者':'继续深入'}</b><small>${cs.length} 个学习地点</small></div>${cs.map(card).join('')}`:n.overview?`<p class="smallnote">本产区当前为概览；多级该产区的酒庄与酒标正在逐步补充。</p><button class="primary" data-place="france">返回法国，选择深度路径</button>`:''}${lesson(n.lesson)}${sourceHTML(n.source)}`}
function sky(n){
 const r=ancestors(n).reverse().find(a=>VINTAGES[a.id]);const years=r?Object.keys(VINTAGES[r.id]).map(Number).sort((a,b)=>a-b):[];const v=r?VINTAGES[r.id][state.year]:null;
 const picker=`<div class="year-picker">${YEARS.map(y=>`<button class="${state.year===y?'active':''}" data-year="${y}" aria-pressed="${state.year===y}">${y}</button>`).join('')}</div>`;
 if(!v)return `<span class="eyebrow">VINTAGE IS LOCAL</span><h2>${state.year} · ${n.name}</h2>${picker}<p class="empty">这个地区的 ${state.year} 年份报告暂未收录。</p>${years.length?`<h3>已有来源的年份</h3><div class="year-picker">${years.map(y=>`<button data-year="${y}">${y}</button>`).join('')}</div>`:''}<p class="smallnote">不会用其他地区的报告或全国统一评分替代。年份背景与酒标图片上的实际年份分开记录。</p>`;
 return `<div class="section-head"><b>${r.name} · 年份对照</b><small>已收录 ${years.join('、')}</small></div>${picker}<div class="year-head"><strong>${state.year}</strong><span>${r.en}</span></div><div>${v.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p class="vintage-lead">${v.title}</p><h3>这一年的天</h3><p class="vintage-detail">${v.weather}</p><h3>如何理解杯中的酒</h3><p class="vintage-detail">${v.style}</p>${lesson(v.question)}<p class="smallnote">以上为${r.name}的区域年份背景，不能替代具体地块或酒款的表现。年份选择不会改变酒标原图的年份。不提供统一分数或固定适饮期限。</p>${sourceHTML([v.source])}`
}

function people(n){if(n.directory)return directoryPanel(n);if(n.kind==='wine')return winePanel(n);if(n.producer)return `<span class="eyebrow">THE HUMAN CHOICE</span><h2>人，如何回应天与地？</h2><p class="vintage-detail">${n.people}</p>${n.estate?estateDetail(n)+estateLabels(n):''}<dl><div class="fact"><dt>关联地点</dt><dd>${ancestors(n).slice(1,-1).map(x=>x.name).join(' · ')}</dd></div></dl>${lesson(n.lesson)}<div class="path-list"><button data-tab-action="sky">结合 ${state.year} 年份背景阅读</button><button data-tab-action="earth">回看葡萄品种与风土</button></div><p class="smallnote">标记为关联地点的近似定位。酒庄可能跨多个产区拥有或经营葡萄园。</p>${relatedWines(n).length?`<h3>从这个生产者继续读酒标</h3>${relatedWines(n).map(card).join('')}`:''}${sourceHTML(n.source)}`;const ps=NODES.filter(x=>x.producer&&(ancestors(x).some(a=>a.id===n.id)||relatedWines(n).some(w=>w.producerId===x.id)));return `<span class="eyebrow">PRODUCERS & DECISIONS</span><h2>同样的天地，不同的选择。</h2><p class="vintage-detail">采收时机、葡萄筛选、萃取、调配与陈酿，都可能改变一杯酒的表达。</p>${ps.length?`<div class="section-head"><b>认识这里的生产者</b><small>${ps.length} 个精选入口</small></div>${ps.map(card).join('')}`:`<p class="empty">此地点尚未收录生产者专题。可返回法国全览选择其他产区继续学习。</p>${[BY_ID.bordeaux,BY_ID.burgundy].map(card).join('')}`}<p class="smallnote">精选学习案例，不是排名，也不是该产区的完整生产者名单。</p>`}

function estateDetail(n){if(n.national)return `<div class="estate-meta"><span class="tag">${escapeHTML(n.tier)}</span><p>${escapeHTML(n.classificationNote||'本地分级主要针对法定产区与具体酒款，不对所有酒庄作统一排名。')}</p><small>${escapeHTML(n.locationNote)}</small></div>`;return `<div class="estate-meta"><span class="tag">${n.tier}</span><p>${n.rank?'1855 分级体系的现行名单；不是具体年份评分。':n.cb2025?'按所列 2025 版 Cru Bourgeois 官方名单展示，适用 2023–2027 年份；历史酒标不回填这一等级。':'未列入本页采用的 1855 列级庄或 2025 Cru Bourgeois 名单；不代表品质评价。'}</p><small>${n.locationNote}</small></div>`}
function directoryEstates(id='pauillac'){return children(id).filter(n=>n.estate)}
function gradeMatch(n,g){return g==='all'||g==='gcc'&&n.rank>0||g==='cb'&&n.cb2025||g==='cb-base'&&n.cb2025&&!n.cbLevel||g==='cb-superieur'&&n.cbLevel==='superieur'||g==='cb-exceptionnel'&&n.cbLevel==='exceptionnel'||g==='other'&&!n.rank&&!n.cb2025||String(n.rank)===g}
function pauillacPanel(){return directoryPanel(BY_ID.pauillac)}

function appellationEstates(n){const ids=new Set(relatedWines(n).map(w=>w.producerId));return NODES.filter(e=>e.producer&&(ids.has(e.id)||ancestors(e).some(a=>a.id===n.id)))}
function nationalDirectoryPanel(n){
 const es=appellationEstates(n),ws=relatedWines(n),types=[...new Set(es.map(e=>e.classificationGroup||e.tier||'生产者'))];
 const filtered=es.filter(e=>(state.grade==='all'||(e.classificationGroup||e.tier||'生产者')===state.grade)&&`${e.name} ${e.en}`.toLowerCase().includes(state.query.toLowerCase()));
 return `<span class="eyebrow">${escapeHTML(n.en.toUpperCase())} / 产区学习档案</span><div class="stat-grid"><div><strong>${es.length}</strong><span>已收录生产者</span></div><div><strong>${ws.length}</strong><span>关联酒款</span></div><div><strong>${mapCoverage(n).located}</strong><span>已有坐标的生产者</span></div></div>${classification(n)}${facts(n)}<p class="smallnote">地图已定位 ${mapCoverage(n).located} / ${es.length} 家；真实酒标 ${mapCoverage(n).labels} / ${ws.length} 款。聚合圆点可点击放大；坐标表示酒庄或接待点，不是葡萄园边界。</p><h3>已收录生产者与分级</h3><div class="grade-filters"><button data-grade="all" class="${state.grade==='all'?'active':''}" aria-pressed="${state.grade==='all'}"><b>${es.length}</b>全部已收录</button>${types.map(t=>`<button data-grade="${escapeHTML(t)}" class="${state.grade===t?'active':''}" aria-pressed="${state.grade===t}"><b>${es.filter(e=>(e.classificationGroup||e.tier||'生产者')===t).length}</b>${escapeHTML(t)}</button>`).join('')}</div><p class="smallnote">上方数字仅统计本图已收录的生产者。一个生产者可酿造多个 AOC；园地、酒款和副牌不重复计作新酒庄。</p><label class="estate-search">查找生产者<input id="estate-search" type="search" placeholder="中文或法文名称" value="${escapeHTML(state.query)}"></label>${filtered.length?filtered.map(e=>card(e)+`<p class="estate-snippet">${escapeHTML(e.profile||e.summary)}</p>`).join(''):'<p class="empty">此分支的生产者尚在补充，可先阅读产区风土。</p>'}${children(n.id).filter(x=>!x.producer&&x.kind!=='wine').length?`<h3>继续读园名或法定产地</h3>${children(n.id).filter(x=>!x.producer&&x.kind!=='wine').map(card).join('')}`:''}${lesson(n.lesson)}${sourceHTML(n.source)}`
}

function directoryPanel(n){
 if(n.nationalDirectory)return nationalDirectoryPanel(n);
 const meta=DIRECTORY_META[n.id],all=directoryEstates(n.id),groups=[['all','全部酒庄'],['gcc','列级庄合计'],['1','一级'],['2','二级'],['3','三级'],['4','四级'],['5','五级'],['cb','Cru Bourgeois 合计'],['other','其他酒庄'],['cb-base','CB 普通级'],['cb-superieur','CB Supérieur'],['cb-exceptionnel','CB Exceptionnel']];
 const filtered=all.filter(e=>gradeMatch(e,state.grade)&&`${e.name} ${e.en}`.toLowerCase().includes(state.query.toLowerCase())),coops=children(n.id).filter(e=>e.cooperative);
 return `<span class="eyebrow">${escapeHTML(n.en.toUpperCase())} / 产区档案</span><div class="stat-grid"><div><strong>${meta.total}</strong><span>${meta.totalLabel}</span></div><div><strong>${all.length}</strong><span>本图已收录酒庄</span></div><div><strong>${all.filter(e=>e.rank).length}</strong><span>列级庄 · 已全部收录</span></div></div><details class="count-scope"><summary>数量口径与来源日期</summary><p>${meta.note} 副牌不重复计数，合作社单列。资料核对：2026-09-29。</p></details><h3>按分级认识酒庄</h3><div class="grade-filters">${groups.map(([g,t])=>`<button data-grade="${g}" aria-pressed="${state.grade===g}" class="${state.grade===g?'active':''}"><b>${all.filter(e=>gradeMatch(e,g)).length}</b>${t}</button>`).join('')}</div><p class="smallnote">一级至五级按 1855 体系现行名单。${meta.cbNote} 该版适用 2023–2027 年份。“其他”是本次收录且不在这两份名单中的酒庄，不是品质评价。</p><label class="estate-search">查找酒庄<input id="estate-search" type="search" placeholder="输入中文或法文名称" value="${escapeHTML(state.query)}"></label><div class="section-head"><b>酒庄名录</b><small>${filtered.length} / ${all.length} 家</small></div><div id="estate-results">${filtered.length?filtered.map(e=>card(e)+`<p class="estate-snippet">${escapeHTML(e.profile)}</p>`).join(''):'<p class="empty">此筛选没有酒庄。可选择全部酒庄重新浏览。</p>'}</div>${coops.length?`<h3>合作社 · 单列 ${coops.length} 家</h3>${coops.map(card).join('')}`:''}<p class="smallnote">地图只展示已有近似坐标的酒庄，其余可从名录进入。村庄层级不显示酒标，进入酒庄或酒款后查看真实酒标。</p>${classification(n)}${sourceHTML(n.source)}`
}
document.addEventListener('input',e=>{if(e.target.id!=='estate-search')return;state.query=e.target.value;const start=e.target.selectionStart;$('#content').innerHTML=directoryPanel(BY_ID[state.id]);const field=$('#estate-search');field.focus();if(field.setSelectionRange)field.setSelectionRange(start,start)});
function estateLabels(n){const ws=relatedWines(n).filter(w=>WINE_IMAGES[w.id]);return `<section class="estate-labels"><div class="section-head"><b>真实酒标</b><small>${ws.length} 款已收录</small></div>${ws.length?`<div class="label-gallery">${ws.map(w=>{const img=WINE_IMAGES[w.id];return `<div><button data-label="${w.id}" aria-label="放大 ${escapeHTML(w.en)} 酒标">${labelImage(img,w.en+"酒标")}</button><button class="text-button" data-place="${w.id}">${escapeHTML(w.en)}</button><small>${imageCaption(img)}</small></div>`}).join('')}</div>`:'<p class="smallnote">暂未找到可核实的独立酒标图，继续补充中。</p>'}</section>`}
function render(){const n=BY_ID[state.id];$('#kind').textContent=n.id==='france'?'FRANCE / 法国学习地图':n.kind==='wine'?'WINE / 具体酒款':['aoc','igp'].includes(n.kind)?'APPELLATION / 法定产地':n.kind==='designation'?'LABEL / 酒标归属':n.kind==='subregion'?'SUBREGION / 地理子产区':n.kind==='climat'?`CLIMAT / ${n.tier}`:n.producer?'PRODUCER / 酒庄与生产者':n.overview?'REGION / 大产区概览':['','REGION / 大产区','SUBREGION / 子产区','APPELLATION / 村庄与法定产区'][depth(n)]||'探索产地';$('#title').textContent=n.id==='france'?'从一片土地，读懂一杯酒。':n.name;$('#enname').textContent=n.id==='france'?'Terroir, through time and people.':n.en;$('#summary').textContent=n.summary;$('#crumbs').innerHTML=ancestors(n).map((a,i)=>`${i?'<span>／</span>':''}<button data-place="${a.id}" ${a.id===state.id?'aria-current="location"':''}>${a.name}</button>`).join('');$('#map-year').value=String(state.year);document.querySelectorAll('[role=tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.tab===state.tab));b.tabIndex=b.dataset.tab===state.tab?0:-1});$('#content').setAttribute('aria-labelledby',`tab-${state.tab}`);$('.tabs').hidden=!!n.producer;$('.map-tools').hidden=!!n.producer;if(n.producer){$('#content').removeAttribute('aria-labelledby');$('#summary').textContent=ancestors(n).slice(1,-1).map(a=>a.name).join(' · ');$('#content').innerHTML=estateProfile(n)}else $('#content').innerHTML=({earth,sky,people})[state.tab](n);renderMarkers()}
function move(n){if(n.id==='france')map.fitBounds([[41.25,-5.2],[51.2,9.8]],{padding:[35,35],animate:false});else map.setView([n.lat,n.lng],n.zoom,{animate:false})}
function select(id){if(!BY_ID[id])return;if(state.id!==id){state.grade='all';state.query=''}state.id=id;move(BY_ID[id]);render();history.replaceState(null,'',`#${id}`);$('aside').scrollTop=0}
function setTab(tab){if(!['earth','sky','people'].includes(tab))return;state.tab=tab;render()}
document.addEventListener('click',e=>{const g=e.target.closest('[data-grade]');if(g){state.grade=g.dataset.grade;render()} const p=e.target.closest('[data-place]');if(p)select(p.dataset.place);const t=e.target.closest('[data-tab]');if(t)setTab(t.dataset.tab);const a=e.target.closest('[data-tab-action]');if(a)setTab(a.dataset.tabAction);const y=e.target.closest('[data-year]');if(y){setYear(Number(y.dataset.year))}const label=e.target.closest('[data-label]');if(label)openLabel(label.dataset.label);});
document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const arr=['earth','sky','people'];let i=arr.indexOf(state.tab);i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setTab(arr[i]);$(`#tab-${arr[i]}`).focus()});
function setYear(y){if(!YEARS.includes(y))return;state.year=y;render()}
function openLabel(id){const img=WINE_IMAGES[id];if(!img)return;$('#label-body').innerHTML=`<span class="eyebrow">真实酒标 / LABEL READING</span><h2>${BY_ID[id].name}</h2>${labelImage(img,img.wine+"真实酒标","large-label")}<p>${imageCaption(img)}</p>${img.crop?'<p class="smallnote">仅显示原照片中的酒标区域，文字未重绘。</p>':''}${img.displayNote?`<p class="smallnote">${escapeHTML(img.displayNote)}</p>`:''}${img.resolutionNote?'<p class="smallnote">此来源图片清晰度有限；请结合文字档案阅读。</p>':''}<p>${BY_ID[id].labelLesson}</p><p class="smallnote">酒标上的历史分级文字反映图示时期；酒庄档案另行标注采用的分级版本。</p><p class="smallnote">${img.visibleVintage?`图片年份为 ${img.visibleVintage}，不随年份选择器改变。`:'此图未能确认年份；不是无年份酒的判断。'}</p><a href="${img.sourcePage}" target="_blank" rel="noopener">查看原始图片来源 · ${img.sourceCredit}</a>`;$('#label-dialog').showModal()}
$('#map-year').innerHTML=YEARS.map(y=>`<option value="${y}">${y}</option>`).join('');$('#map-year').onchange=e=>setYear(Number(e.target.value));$('#labels-toggle').onchange=e=>{state.labels=e.target.checked;renderMarkers()};$('#close-label').onclick=()=>$('#label-dialog').close();
$('#home').onclick=()=>{state.tab='earth';select('france')};$('.brand').onclick=e=>{e.preventDefault();state.tab='earth';select('france')};$('#about').onclick=()=>$('#about-dialog').showModal();$('#close-about').onclick=$('#start').onclick=()=>$('#about-dialog').close();window.addEventListener('hashchange',()=>{if(BY_ID[location.hash.slice(1)])select(location.hash.slice(1))});
select(BY_ID[location.hash.slice(1)]?location.hash.slice(1):'france');

function estateWineGroup(w){if(/副牌/.test(w.tier||''))return '副牌酒';if(/正牌|酒庄同名/.test(w.tier||''))return '主牌酒';return '其他酒款与园地酒'}
function estateProfile(n){const p=ESTATE_PROFILES[n.id],photos=ESTATE_PHOTOS[n.id]||[],wines=NODES.filter(w=>w.kind==='wine'&&w.producerId===n.id&&(!state.mangaOnly||MANGA_BY_ID[w.id]));const groups=['主牌酒','副牌酒','其他酒款与园地酒'];return `<article class="estate-profile">${photos.length?`<div class="estate-photos">${photos.map(photo=>`<figure><img src="${photo.src}" alt="${escapeHTML(photo.caption)}" width="${photo.width}" height="${photo.height}" loading="lazy" decoding="async"><figcaption>${escapeHTML(photo.caption)} · <a href="${photo.source}" target="_blank" rel="noopener">${escapeHTML(photo.credit)}</a></figcaption></figure>`).join('')}</div>`:''}<section><h2>酒庄介绍</h2><p>${escapeHTML(p?.intro||n.profile||n.summary||n.people||'酒庄介绍待补充。')}</p>${n.tier?`<p class="estate-rank">${escapeHTML(n.tier)}</p>`:''}</section>${p?.details?.length?`<section><h2>酒庄资料</h2><dl class="estate-details">${p.details.map(([key,value])=>`<dt>${escapeHTML(key)}</dt><dd>${escapeHTML(value)}</dd>`).join('')}</dl></section>`:''}${p?.coverage?`<p class="smallnote">资料状态：${escapeHTML(p.coverage)}</p>`:''}${p?.history?.length?`<section><h2>历史沿革</h2><ol class="estate-history">${p.history.map(([year,event])=>`<li><strong>${escapeHTML(year)}</strong><p>${escapeHTML(event)}</p></li>`).join('')}</ol></section>`:''}${n.locationNote?`<p class="smallnote">地图位置：${escapeHTML(n.locationNote)}</p>`:''}<section class="estate-wine-index"><div class="section-head"><h2>旗下酒款</h2><small>${wines.length} 款已收录</small></div>${groups.map(group=>{const ws=wines.filter(w=>estateWineGroup(w)===group);return ws.length?`<section><h3>${group}</h3>${ws.map(card).join('')}</section>`:''}).join('')}${!wines.length?'<p class="smallnote">具体酒款资料待补充。</p>':''}<p class="smallnote">这里列出已收录的酒款，不代表酒庄完整产品线；具体年份在酒款页查看和收藏。</p></section>${p?.sources?.length?`<details class="sources"><summary>酒庄介绍与历史来源</summary>${p.sources.map((url,i)=>`<a href="${url}" target="_blank" rel="noopener">酒庄历史资料 ${i+1}</a>`).join('')}</details>`:''}${sourceHTML(n.source||[])}</article>`}
