'use strict';
const catalog=Object.fromEntries([...NODES.filter(n=>n.kind==='wine').map(n=>({...n,producer:BY_ID[n.producerId]?.en,place:ancestors(n).slice(1,-1).map(a=>a.name).join(' · ')})),...APOSTLES].map(n=>[n.id,n]));
const collection={items:[],loaded:false,error:'',busy:new Set(),years:{},mode:'map',selected:null};
const baseRender=render,baseMarkers=renderMarkers,baseWinePanel=winePanel,baseSelect=select;
const themeMarkers=L.layerGroup().addTo(map);
map.off('zoomend',baseMarkers);map.off('moveend',baseMarkers);map.on('zoomend',()=>renderMarkers());map.on('moveend',()=>renderMarkers());
map.setMinZoom(2);map.setMaxBounds([[-70,-180],[80,180]]);
const favKey=(id,year)=>id+'|'+year;
const hasFavorite=(id,year)=>collection.items.some(f=>f.wineId===id&&f.vintage===year);
const chosenYear=n=>collection.years[n.id]||n.vintage||String(state.year);
function favoriteControls(n){const year=chosenYear(n),saved=hasFavorite(n.id,year),busy=collection.busy.has(favKey(n.id,year));return `<div class="favorite-box" data-fav-box="${n.id}"><label>收藏年份<select data-fav-year="${n.id}" aria-label="${escapeHTML(n.name)}收藏年份">${['NV',...Array.from({length:new Date().getFullYear()-1699},(_,i)=>String(new Date().getFullYear()-i))].map(y=>`<option value="${y}" ${y===year?'selected':''}>${y==='NV'?'NV · 无年份':y}</option>`).join('')}</select></label><button class="favorite-button ${saved?'saved':''}" data-save="${n.id}" aria-pressed="${saved}" ${busy||!collection.loaded?'disabled':''}>${busy?'保存中…':saved?'★ 已收藏 · 取消':'☆ 收藏这款 · '+year}</button><small>记录具体酒款与年份。可手动选择其他年份；年份选项不表示该年一定出产。</small></div>`}
winePanel=function(n){return baseWinePanel(n)+favoriteControls(catalog[n.id])+statusHTML()};
function statusHTML(){return collection.error?`<p class="save-error" role="alert">${escapeHTML(collection.error)} <button data-retry>重试读取</button></p>`:!collection.loaded?'<p role="status">正在读取收藏…</p>':''}
function syncBoxes(){document.querySelectorAll('[data-fav-box]').forEach(el=>{const n=catalog[el.dataset.favBox];if(n)el.outerHTML=favoriteControls(n)});$('#collection-nav').textContent=`我的收藏${collection.loaded?' · '+collection.items.length:''}`}
async function loadFavorites(){collection.error='';try{const r=await fetch('/api/favorites',{cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await r.json();if(!r.ok)throw Error(data.error||'无法读取收藏。');collection.items=data.items;collection.loaded=true;}catch(e){collection.error=e.message;collection.loaded=false}if(collection.mode!=='map')renderTheme();else render();syncBoxes()}
async function toggleFavorite(id,year){const key=favKey(id,year);if(collection.busy.has(key)||!collection.loaded)return;const saved=hasFavorite(id,year);collection.busy.add(key);collection.error='';syncBoxes();try{const r=await fetch('/api/favorites',{method:saved?'DELETE':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({wineId:id,vintage:year})});const d=await r.json();if(!r.ok)throw Error(d.error||'收藏保存失败，请重试。');collection.items=collection.items.filter(f=>favKey(f.wineId,f.vintage)!==key);if(!saved)collection.items.unshift({wineId:id,vintage:year});$('#collection-status').textContent=saved?'已取消收藏':'已收藏 '+catalog[id].name+' · '+year;}catch(e){collection.error=e.message;$('#collection-status').textContent=e.message;}finally{collection.busy.delete(key);if(collection.mode!=='map')renderTheme();else render();syncBoxes()}}
function apostleCard(n){return `<article class="apostle-card"><div class="apostle-heading"><span class="apostle-number">${String(n.apostle).padStart(2,'0')}</span><div><span class="eyebrow">第 ${n.apostle} 使徒 · ${n.type}</span><h2>${n.name}</h2></div><b class="apostle-vintage">${n.vintage}</b></div><p class="wine-en">${escapeHTML(n.en)}</p><p class="producer-name">${escapeHTML(n.producer)}</p><p class="apostle-place">${n.place}</p><button class="plain" data-apostle="${n.id}">地图定位与详情</button>${mangaLabel(n)}${favoriteControls(n)}</article>`}
function renderTheme(){
 const selected=collection.selected?catalog[collection.selected]:null;
 $('#kind').textContent=collection.mode==='apostles'?'THE TWELVE APOSTLES / 神之水滴':'MY COLLECTION / 我的收藏';
 $('#title').textContent=collection.mode==='apostles'?(selected?.name||'沿十二使徒，读懂天地人。'):'每一瓶，都有自己的年份。';
 $('#enname').textContent=selected?.en||'';
 $('#summary').textContent=collection.mode==='apostles'?'原作漫画的十二款答案，按使徒顺序排列。包含谜底。':'收藏标记按酒款与年份保存；不代表实物持有数量。';
 $('.tabs').hidden=true;$('#village-summary').hidden=true;$('#selected-label').hidden=true;$('.map-tools').hidden=true;
 $('#crumbs').innerHTML=`<button data-mode="map">法国地图</button><span>／</span><button data-mode="${collection.mode}">${collection.mode==='apostles'?'十二使徒':'我的收藏'}</button>`;
 $('#content').removeAttribute('aria-labelledby');
 if(collection.mode==='apostles'){
  const rows=selected?[selected]:APOSTLES;
  $('#content').innerHTML=`${selected?'<button class="plain" data-all-apostles>返回十二使徒全览</button>':''}${statusHTML()}${rows.map(apostleCard).join('')}${selected?`<div class="lesson"><strong>核对这瓶酒</strong><p>${selected.note}</p></div><p class="smallnote">地图点位为产地或关联地点的近似定位，不代表葡萄园边界。</p>${selected.placeId&&BY_ID[selected.placeId]?`<button class="primary" data-place="${selected.placeId}">深入${BY_ID[selected.placeId].name}产区</button>`:''}`:''}<details class="sources"><summary>酒款与年份资料来源</summary><a href="https://www.drops-of-god.com/en/apostles/" target="_blank" rel="noopener">Drops of God Wines · 十二使徒整理</a><a href="https://comic-gourmet.com/the-drop-of-god-apostles/" target="_blank" rel="noopener">Comic Gourmet · 原作漫画酒款对照</a><p>依据两份漫画酒单交叉核对，不混用电视剧或竞争者的错误候选答案。酒标尚未核实时不以整瓶图或其他年份图片替代。</p></details>`;
 }else{
  $('#content').innerHTML=`${statusHTML()}${collection.loaded&&!collection.items.length?'<div class="empty">还没有收藏。进入具体酒款，选好年份后点击星标。</div><button class="primary" data-mode="map">从产区地图开始</button>':''}${collection.items.map(f=>{const n=catalog[f.wineId];return n?`<article class="favorite-item"><span class="eyebrow">${n.apostle?'第 '+n.apostle+' 使徒酒款':'地图酒款'}${n.apostle&&f.vintage!==n.vintage?' · 非漫画原年份':''}</span><h2>${escapeHTML(n.name)} <b>${f.vintage}</b></h2><p>${escapeHTML(n.producer)} · ${escapeHTML(n.en)}</p><button class="plain" data-open-wine="${n.id}" data-open-year="${f.vintage}">查看酒款</button><button class="remove-favorite" data-remove-wine="${n.id}" data-remove-year="${f.vintage}" ${collection.busy.has(favKey(n.id,f.vintage))?'disabled':''}>取消收藏</button></article>`:''}).join('')}`;
 }
 renderMarkers();syncBoxes();
}
render=function(){if(collection.mode==='map'){ $('.tabs').hidden=false;$('.map-tools').hidden=false;baseRender();}else renderTheme()};
renderMarkers=function(){if(collection.mode==='map'){themeMarkers.clearLayers();baseMarkers();return}markers.clearLayers();themeMarkers.clearLayers();$('#village-summary').hidden=true;$('#selected-label').hidden=true;const rows=collection.mode==='apostles'?APOSTLES:[...new Set(collection.items.map(x=>x.wineId))].map(id=>catalog[id]).filter(Boolean);for(const n of rows){if(n.lat==null)continue;const saved=collection.items.some(f=>f.wineId===n.id);L.marker([n.lat,n.lng],{icon:L.divIcon({className:'atlas-marker',html:`<button class="apostle-pin ${collection.selected===n.id?'selected':''}" aria-label="${escapeHTML(n.name)}"><b>${n.apostle?String(n.apostle).padStart(2,'0'):'★'}</b><span>${escapeHTML(n.name)}${saved?' ★':''}</span></button>`,iconSize:[20,20],iconAnchor:[10,10]}),title:n.name}).on('click',()=>openWine(n.id)).addTo(themeMarkers)}$('#level').textContent=collection.mode==='apostles'?'专题 / 十二使徒':'收藏 / 酒款与年份';};
select=function(id){collection.mode='map';collection.selected=null;themeMarkers.clearLayers();baseSelect(id);updateNav()};
function updateNav(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===collection.mode)))}
function setMode(mode){collection.mode=mode;collection.selected=null;updateNav();if(mode==='map'){select(state.id);return}map.fitBounds(mode==='apostles'?[[32,-124],[51,13]]:[[42,-5],[51,9]],{padding:[35,35],animate:false});history.replaceState(null,'','#'+mode);renderTheme();$('aside').scrollTop=0;}
function openWine(id,year){const n=catalog[id];if(!n)return;if(year)collection.years[id]=year;if(!n.apostle){state.tab='earth';select(id);return}collection.mode='apostles';collection.selected=id;updateNav();map.setView([n.lat,n.lng],12,{animate:false});renderTheme();$('aside').scrollTop=0;history.replaceState(null,'','#apostle-'+n.apostle)}
function navigateMode(mode){try{setMode(mode)}catch(error){console.error('Navigation failed',error);const status=$('#collection-status');status.textContent='页面切换未完成，请刷新后重试。';}}
// Bind the persistent navigation directly: embedded hosts may intercept bubbling clicks.
$('.feature-nav').addEventListener('click',e=>{const button=e.target.closest('[data-mode]');if(!button)return;e.preventDefault();e.stopPropagation();navigateMode(button.dataset.mode)});
document.addEventListener('click',e=>{const mode=e.target.closest('[data-mode]');if(mode)navigateMode(mode.dataset.mode);const pin=e.target.closest('[data-apostle]');if(pin)openWine(pin.dataset.apostle);if(e.target.closest('[data-all-apostles]'))setMode('apostles');const fav=e.target.closest('[data-save]');if(fav)toggleFavorite(fav.dataset.save,chosenYear(catalog[fav.dataset.save]));const remove=e.target.closest('[data-remove-wine]');if(remove)toggleFavorite(remove.dataset.removeWine,remove.dataset.removeYear);const open=e.target.closest('[data-open-wine]');if(open)openWine(open.dataset.openWine,open.dataset.openYear);if(e.target.closest('[data-retry]'))loadFavorites()});
document.addEventListener('change',e=>{if(e.target.matches('[data-fav-year]')){collection.years[e.target.dataset.favYear]=e.target.value;syncBoxes()}});
loadFavorites();
