// The geography tree is for navigation. AOC status and producer relations remain separate.
Object.assign(SOURCES,{
 aoc:['勃艮第协会 · AOC 与附加地理名称','https://www.bourgogne-wines.com/wine-and-terroir/decoding-the-aocs/bourgogne-wines-decoding-the-aocs,2467,9263.html'],
 vosne:['勃艮第协会 · Vosne-Romanée 产区档案','https://www.bourgogne-wines.com/wine-and-terroir/bourgogne-and-its-appellations/gallery_files/site/321/402/79294/79831.pdf'],
 gevrey:['勃艮第协会 · Gevrey-Chambertin','https://www.bourgogne-wines.com/wine-and-terroir/bourgogne-and-its-appellations/gevrey-chambertin,2458,9253.html?args=Y29tcF9pZD0yMjc4JmFjdGlvbj12aWV3RmljaGUmaWQ9MzA5Jnw%3D'],
 pommard:['勃艮第协会 · Pommard 产区档案','https://www.bourgogne-wines.com/our-wines-our-terroir/bourgogne-and-its-appellations/gallery_files/site/321/402/57644/57704.pdf'],
 pavillon:['玛歌酒庄 · Pavillon Rouge','https://chateau-margaux.com/en/vins/pavillon-rouge-du-chateau-margaux'],
 grandmargaux:['玛歌酒庄 · Grand Vin','https://chateau-margaux.com/en/vins/grand-vin-du-chateau-margaux'],
 tache:['DRC · La Tâche','https://www.romanee-conti.fr/fr/9-grand-crus/5/la-tache'],
 richebourg:['DRC · Richebourg','https://www.romanee-conti.fr/fr/9-grand-crus/6/richebourg'],
 bguide:['波尔多协会 · 2010–2020 年份回顾','https://www.bordeaux.com/fr/mag/blog/l-indispensable-guide-des-millesimes-a-bordeaux/'],
 uarchive:['勃艮第协会 · 历年年份报告','https://www.bourgogne-wines.com/press/vintages,2333,9343.html?args=Y29tcF9pZD0xNDczJmFjdGlvbj12aWV3QWxsQ29tbXVuaXF1ZSZpZD0yJmFydGljbGVfbGliZWxsZT1WaW50YWdlc3w%3D']
});
function namedPlot(id,parent,name,en,lat,lng,tier,label,summary,src){node(id,parent,name,en,lat,lng,16,summary,'黑皮诺','园地定位为近似中心；不表示法定边界或生产者持有范围。','年份参考勃艮第大区，具体地块的局部差异需另行考察。','在酒标上依次寻找：法定产区、园名／等级、生产者、年份。',[src,'aoc'],{kind:'climat',tier,labelText:label,relationNote:tier==='特级园 AOC'?'在地理上关联该村庄；该特级园拥有独立 AOC，并非村庄 AOC 内的一级园。':'属于村庄 AOC 下的 Premier Cru 地理名称；不是另一个独立的特级园 AOC。'})}
namedPlot('suchots','vosne','苏秀园','Les Suchots',47.1655,4.954,'一级园','Vosne-Romanée Premier Cru · Les Suchots','酒标保留 Vosne-Romanée 村庄产区名，再叠加 Premier Cru 和园名。','vosne');
namedPlot('malconsorts','vosne','玛康索园','Aux Malconsorts',47.153,4.948,'一级园','Vosne-Romanée Premier Cru · Aux Malconsorts','用“村庄＋一级园＋园名”的组合，识别比村庄级更细的地理来源。','vosne');
namedPlot('romanee-conti','vosne','罗曼尼康帝园','Romanée-Conti',47.1613,4.9508,'特级园 AOC','Romanée-Conti Grand Cru','这里的 Romanée-Conti 是独立特级园 AOC；不要和生产者 Domaine de la Romanée-Conti 混淆。','vosne');
namedPlot('la-tache','vosne','拉塔希园','La Tâche',47.157,4.9476,'特级园 AOC','La Tâche Grand Cru','在酒标上，La Tâche 本身就是特级园产地名称，不需要用 Vosne-Romanée Premier Cru 表示。','tache');
namedPlot('richebourg','vosne','李奇堡园','Richebourg',47.1635,4.951,'特级园 AOC','Richebourg Grand Cru','园名指向地理来源；生产者名则告诉你由谁种植或酿造。二者是不同的信息。','richebourg');
namedPlot('clos-jacques','gevrey','圣雅克园','Clos Saint-Jacques',47.231,4.961,'一级园','Gevrey-Chambertin Premier Cru · Clos Saint-Jacques','即使园名知名，仍应以酒标标示的 Premier Cru 等级理解它。','gevrey');
namedPlot('chambertin','gevrey','香贝丹园','Chambertin',47.211,4.961,'特级园 AOC','Chambertin Grand Cru','Chambertin 特级园与 Gevrey-Chambertin 村庄级酒标，指向不同的法定产地。','gevrey');
namedPlot('rugiens','pommard','鲁吉安园','Les Rugiens',47.0025,4.789,'一级园','Pommard Premier Cru · Les Rugiens','Pommard 的著名一级园名称。名气并不把它自动变成 Grand Cru。','pommard');
namedPlot('epenots','pommard','埃佩诺园','Les Épenots',47.0155,4.802,'一级园','Pommard Premier Cru · Les Épenots','在同一村庄下，以具名园地继续提高酒标的地理颗粒度。','pommard');
function wine(id,parent,name,en,producerId,labelText,source,extra={}){const p=NODES.find(n=>n.id===parent);node(id,parent,name,en,p.lat,p.lng,17,'把产地、生产者和酒款名称放在同一张酒标上阅读。',p.grapes,p.soil,p.climate,'先确认这是什么酒款，再看酒标上的具体年份。',source,{kind:'wine',producerId,labelText,tier:extra.tier||'具体酒款',...extra})}
wine('margaux-grand','ch-margaux','玛歌正牌','Château Margaux','ch-margaux','Château Margaux · Margaux',['grandmargaux'],{tier:'正牌酒',labelLesson:'Château Margaux 是酒庄与正牌酒名称；Margaux 是 AOC。Premier Grand Cru Classé 表示酒庄分级，并不是更小的地理产区。'});
wine('margaux-pavillon','ch-margaux','玛歌红亭','Pavillon Rouge du Château Margaux','ch-margaux','Pavillon Rouge du Château Margaux · Margaux',['pavillon'],{tier:'副牌酒',labelLesson:'同一酒庄、同一 AOC，Pavillon Rouge 与 Château Margaux 是不同酒款。副牌酒不是更小一级的地理产区。'});
wine('mouton-grand','mouton','木桐正牌','Château Mouton Rothschild','mouton','Château Mouton Rothschild · Pauillac',['mouton'],{tier:'正牌酒',labelLesson:'酒庄名称、Pauillac 产地与年份分别提供三类信息；艺术酒标也随年份改变。'});
wine('cheval-grand','cheval','白马正牌','Château Cheval Blanc','cheval','Château Cheval Blanc · Saint-Émilion Grand Cru',['cheval'],{tier:'正牌酒',labelLesson:'Saint-Émilion Grand Cru 是 AOC 名称；不要与 Grand Cru Classé 的酒庄分级混淆，也不要套用勃艮第特级园的含义。'});
wine('drc-rc','romanee-conti','DRC · 罗曼尼康帝','Romanée-Conti · Domaine de la Romanée-Conti','drc','Romanée-Conti Grand Cru · Domaine de la Romanée-Conti',['drc'],{tier:'特级园酒款',labelLesson:'Romanée-Conti 指园地和 AOC；Domaine de la Romanée-Conti 指生产者。两者同名但不是同一概念。'});
wine('drc-tache','la-tache','DRC · 拉塔希','La Tâche · Domaine de la Romanée-Conti','drc','La Tâche Grand Cru · Domaine de la Romanée-Conti',['tache'],{tier:'特级园酒款',labelLesson:'La Tâche 是产地；Domaine de la Romanée-Conti 是生产者；Monopole 表示独占，并不是比 Grand Cru 更高的法定等级。'});
wine('drc-richebourg','richebourg','DRC · 李奇堡','Richebourg · Domaine de la Romanée-Conti','drc','Richebourg Grand Cru · Domaine de la Romanée-Conti',['richebourg'],{tier:'特级园酒款',labelLesson:'同一生产者的不同特级园，是观察地块差异的入口；同一园名也可由不同生产者出品。'});
const YEARS=Array.from({length:10},(_,i)=>2015+i);
function vintage(r,y,title,tags,weather,style,question,source){VINTAGES[r][y]={title,tags,weather,style,question,source}}
for(const y of [2016,2018,2019,2020,2023,2024])SOURCES['b'+y]=['波尔多协会 · '+y,'https://www.bordeaux.com/fr/millesimes/'+y+'/'];
vintage('bordeaux',2015,'成熟与结构，是这一年的学习线索',['成熟','结构','集中度'],'温暖而阳光充足的条件帮助葡萄成熟；不同地块仍有差异。','协会回顾强调红葡萄酒的结构与密度。不要将大区声誉直接当作每瓶酒的评分。','成熟果实与单宁结构，在你选定的酒款里是否保持平衡？','bguide');
vintage('bordeaux',2016,'采收前的雨与秋日阳光',['九月降雨','成熟','平衡'],'九月初降雨之后，晴朗的秋季帮助葡萄完成成熟。','协会强调黑色水果、圆润单宁与整体平衡。','同样成熟的葡萄，在两岸不同土壤上会如何表达？','b2016');
vintage('bordeaux',2017,'霜冻改变的是产量，也改变选择',['霜冻','减产','地块差异'],'春季霜冻重创部分产区，受影响程度因地块而异。','幸免地块与受损地块不能一概而论。协会回顾强调部分红酒的柔顺与清新。','少产是否等于更浓郁？先看减产发生的原因。','bguide');
vintage('bordeaux',2018,'温暖成熟，仍要看地块与选择',['炎热','成熟果实','集中度'],'七月中旬至采收季，稳定而温暖的天气有利于成熟。','红葡萄酒常以成熟果实、饱满度和结构作为学习线索。','如何区分果实成熟感与橡木桶带来的甜香？','b2018');
vintage('bordeaux',2019,'把注意力放在成熟与平衡',['成熟','结构','平衡'],'生长季仍需持续应对天气变化；梅洛与赤霞珠的采收节奏并不相同。','协会回顾强调红酒的结构与平衡；具体酒款的酒精度应以酒标为准。','同一年份，调配比例如何影响你感到的结构？','b2019');
vintage('bordeaux',2020,'早熟年份的平衡课',['生长提前','较早采收','平衡'],'葡萄生长各阶段较早，最早地块的梅洛九月初已开始采收。','协会强调酒精、酸度与单宁之间的协调。','采收提前是否一定导致风格变轻？请回到具体酒款观察。','b2020');
vintage('bordeaux',2023,'潮湿与高温交替的一年',['霉菌压力','夏季转热','风格多样'],'六月降雨带来霉菌压力，之后夏季转暖，采收前的天气再次影响成熟。','协会强调清晰果味、酸度与多样性；地块和酿造选择影响显著。','同样的天气压力，梅洛与赤霞珠会受到一样的影响吗？','b2023');
vintage('bordeaux',2024,'湿润年份，更考验筛选与时机',['春季多雨','低产','精准采收'],'春季多雨、霉菌压力大，生长节奏受到干扰；夏季后段改善。','协会早期评价强调细腻与清晰果味，不能按炎热年份的密度去要求它。','有条件等待的赤霞珠，与早采的地块，会有何差别？','b2024');
const UREPORTS={2015:'https://www.bourgogne-wines.com/press/the-2015-vintage-simply-sublime,2333,9344.html?args=Y29tcF9pZD0xNDc1JmFjdGlvbj12aWV3RGV0YWlsQ29tbXVuaXF1ZSZpZD04OTkmYXJ0aWNsZV9saWJlbGxlPVRoZSsyMDE1K1ZpbnRhZ2UlM0ErU2ltcGx5K1N1YmxpbWUlMjF8',2016:'https://www.bourgogne-wines.com/press/the-2016-vintage-in-the-bourgogne-a-pleasant-surprise,2333,9344.html?args=Y29tcF9pZD0xNDc1JmFjdGlvbj12aWV3RGV0YWlsQ29tbXVuaXF1ZSZpZD04OTImYXJ0aWNsZV9saWJlbGxlPVRoZSsyMDE2K1ZpbnRhZ2UraW4rdGhlK0JvdXJnb2duZSUzQSthK3BsZWFzYW50K3N1cnByaXNlfA%3D%3D',2017:'https://www.bourgogne-wines.com/press/the-2017-vintage-the-epitome-of-bourgogne-elegance,2333,9344.html?args=Y29tcF9pZD0xNDc1JmFjdGlvbj12aWV3RGV0YWlsQ29tbXVuaXF1ZSZpZD0xMDM5JmFydGljbGVfbGliZWxsZT1UaGUrMjAxNytWaW50YWdlJTJDK3RoZStlcGl0b21lK29mK0JvdXJnb2duZStlbGVnYW5jZXw%3D',2018:'https://www.bourgogne-wines.com/press/bourgogne-2018-an-ideal-vintage,2333,9344.html?args=Y29tcF9pZD0xNDc1JmFjdGlvbj12aWV3RGV0YWlsQ29tbXVuaXF1ZSZpZD0xNTA4JmFydGljbGVfbGliZWxsZT1Cb3VyZ29nbmUrMjAxOCUzQStBbitpZGVhbCt2aW50YWdlfA%3D%3D'};
for(const y of [2015,2016,2017,2018])SOURCES['u'+y]=['勃艮第协会 · '+y+' 年份报告',UREPORTS[y]];
vintage('burgundy',2015,'阳光年份的成熟果实',['健康果实','成熟','饱满'],'协会记录了良好的果实健康状态与成熟度。','回顾强调阳光年份的丰沛表达。仍需区分园地与生产者。','成熟感是否掩盖了园地差异，还是让差异更清晰？','u2015');
vintage('burgundy',2016,'少量收成，不妨碍精彩表达',['四月霜冻','冰雹','降雨'],'四月底霜冻波及广泛，局部冰雹与降雨进一步增加难度。','产量少，但协会在采收一年后给出积极评价；损失与酒质不是同一指标。','同一村庄内，为什么相邻地块的收成可能差别很大？','u2016');
vintage('burgundy',2017,'产量回升，优雅的观察样本',['收成恢复','果味','优雅'],'经历多年的天气挑战后，2017 的收成较为充足。','协会以优雅概括这批酒。比较时仍应锁定相同酒款与生产者。','“优雅”对你而言是香气、单宁触感，还是酒体重量？','u2017');
vintage('burgundy',2018,'冬季蓄水，迎接炎热夏天',['冬雨','炎热干燥','健康收成'],'冬季降雨储备水分，随后迎来炎热干燥的夏季；采收从八月下旬延续至九月。','协会强调产量与质量兼具，成熟与丰沛是可关注的线索。','冬季储水如何影响葡萄藤面对夏季干旱的表现？','u2018');
vintage('burgundy',2019,'在变化中观察年份的潜力',['年份回顾','品质表现','生产者差异'],'协会将这一年描述为具有变化的一年；详细气候过程可阅读其原始年份报告。','采收一年后的官方回顾给出积极评价。这里不以数字分数替代地块差异。','同一生产者的两个园，在同一年里会保留哪些个性？','uarchive');
vintage('burgundy',2020,'特殊的一年，回到酒本身',['生产挑战','年份回顾','平衡判断'],'疫情改变了生产组织；协会回顾同时强调这是一个有个性的成功年份。','质量判断仍需回到具体园地、采收选择与酒款，不把整个大区视为一个味道。','把 2020 与 2021 并排品尝，哪些差别最容易被你识别？','uarchive');
vintage('burgundy',2023,'连续两年的充足收成',['收成充足','库存恢复','酒款差异'],'继 2022 后，2023 再次获得高于平均水平的收成。','官方初期评价积极；较高产量本身不等于稀薄，需回到具体酒款。','产量、浓度和质量之间，是否存在简单的线性关系？','uarchive');
vintage('burgundy',2024,'生长季充满挑战，收成偏少',['生长挑战','收成偏少','早期评价'],'协会指出整个生长周期都面临挑战，产量明显不如前一年充足。','官方采后评价保持积极；这是早期年份判断，不能替代长期瓶陈表现。','在困难年份，人的筛选和地块条件分别起多大作用？','uarchive');
const WINE_IMAGES={};
SOURCES.faiveley=['Faiveley 伏旧园 · 官方进口商 Wilson Daniels','https://wilsondaniels.com/wine/domaine-faiveley/clos-de-vougeot-grand-cru/'];
node('vougeot','nuits','伏旧','Vougeot',47.176,4.964,14,'村庄名 Vougeot 与特级园名 Clos de Vougeot，是两个不同的酒标信息。','黑皮诺（本版红葡萄酒路径）','坡地与局部地质差异需按具体园地考察。','偏大陆性气候。','Clos de Vougeot 是特级园 AOC，Vougeot 村庄产区另有自己的酒款。',['aoc','faiveley']);
namedPlot('clos-vougeot','vougeot','伏旧园','Clos de Vougeot',47.174,4.956,'特级园 AOC','Clos de Vougeot Grand Cru','同一特级园由不同生产者出品；这正是把“地”与“人”分开学习的好例子。','faiveley');
node('faiveley','nuits','法维莱酒庄','Domaine Faiveley',47.135,4.95,13,'总部关联夜圣乔治，酒款则可来自不同村庄与园地。','依具体酒款而异','请按酒标所示园地阅读，而不是按酒庄驻地推断。','具体酒款应关联其来源地的年份条件。','产地与生产者是多对多关系，酒庄驻地并不限定其全部酒款。',['faiveley'],{producer:true,people:'本版用 Clos de Vougeot Grand Cru 展示生产者、特级园与年份三个独立字段。'});
wine('faiveley-vougeot','clos-vougeot','Faiveley · 伏旧园','Clos de Vougeot Grand Cru · Domaine Faiveley','faiveley','Clos de Vougeot Grand Cru · Domaine Faiveley',['faiveley'],{tier:'特级园酒款',labelLesson:'Clos de Vougeot 是特级园产地；Domaine Faiveley 是生产者；Depuis 1825 表示创立年份，不是葡萄采收年份。'});
WINE_IMAGES["margaux-grand"]={"file": "margaux-2023-label.webp", "wine": "Château Margaux Grand Vin", "visibleVintage": "2023", "kind": "label", "sourcePage": "https://chateau-margaux.com/en/vins/grand-vin-du-chateau-margaux-2023", "imageUrl": "https://framerusercontent.com/images/SPcIjxmJByYQIj1uVrvcsZmX8.webp?width=540&height=399", "sourceCredit": "Château Margaux (official producer)", "src": "labels/margaux-2023-label.webp"};
WINE_IMAGES["margaux-pavillon"]={"file": "pavillon-rouge-label.webp", "wine": "Pavillon Rouge du Château Margaux", "visibleVintage": "2020", "kind": "label", "sourcePage": "https://chateau-margaux.com/en/vins/pavillon-rouge-du-chateau-margaux-2020", "imageUrl": "https://framerusercontent.com/images/3KrARPVhF0x4BLpn2BkZHH6ZE.webp?width=540&height=398", "sourceCredit": "Château Margaux (official producer)", "src": "labels/pavillon-rouge-label.webp"};
WINE_IMAGES["mouton-grand"]={"file": "mouton-2020.jpg", "wine": "Château Mouton Rothschild", "visibleVintage": "2020", "kind": "bottle", "sourcePage": "https://www.chateau-mouton-rothschild.com/chateau-mouton-rothschild/chateau-mouton-rothschild-2020", "imageUrl": "https://www.chateau-mouton-rothschild.com/cellar/uploads/Packshot_Chateau_Mouton_Rothschild_2020_210.jpg", "sourceCredit": "Château Mouton Rothschild (official producer); label art Peter Doig", "src": "labels/mouton-2020.jpg"};
WINE_IMAGES["cheval-grand"]={"file": "cheval-blanc-2020.png", "wine": "Château Cheval Blanc", "visibleVintage": "2020", "kind": "bottle", "sourcePage": "https://www.chateau-cheval-blanc.com/en/vin/chateau-cheval-blanc/", "imageUrl": "https://www.chateau-cheval-blanc.com/wp-content/uploads/2023/11/2020.png", "sourceCredit": "Château Cheval Blanc (official producer)", "note": "Label reflects historical Premier Grand Cru Classé A wording of 2020; do not use that classification as current estate status.", "src": "labels/cheval-blanc-2020.png"};
WINE_IMAGES["faiveley-vougeot"]={"file": "faiveley-clos-vougeot-label.jpg", "wine": "Domaine Faiveley Clos de Vougeot Grand Cru", "visibleVintage": null, "kind": "label", "sourcePage": "https://wilsondaniels.com/wine/domaine-faiveley/clos-de-vougeot-grand-cru/", "imageUrl": "https://images.salsify.com/images/defce21374e9e25fac19b55953aaf68109ed9de5/DF_NV_CLOS_DE_VOUGEOT.jpg", "sourceCredit": "Wilson Daniels (official importer), Domaine Faiveley", "note": "No vintage printed. 1825 is producer founding year, not vintage.", "src": "labels/faiveley-clos-vougeot-label.jpg"};
WINE_IMAGES["drc-tache"]={"file": "drc-la-tache-label.png", "wine": "Domaine de la Romanée-Conti La Tâche", "visibleVintage": null, "kind": "label", "sourcePage": "https://wilsondaniels.com/wine/domaine-de-la-romanee-conti/la-tache-grand-cru-monopole/", "imageUrl": "https://images.salsify.com/images/rnssj323montds1maxos/DRC_NV_-23_LaTache_Lbl.png", "sourceCredit": "Wilson Daniels (official importer), Domaine de la Romanée-Conti", "note": "No vintage printed. Filename -23 does not establish visible vintage. Label reads 26.887 Bouteilles Récoltées, Pierre de Villaine, B. de Villaine.", "src": "labels/drc-la-tache-label.png"};
