'use strict';
// Extend the existing catalog; preserve canonical IDs and saved favorites.
for(const n of MANGA_WINES){if(catalog[n.id])Object.assign(catalog[n.id],{manga:n.manga,mangaKey:n.mangaKey,reviewStatus:n.reviewStatus});else catalog[n.id]=n;}
collection.search='';collection.series='';collection.volume='';collection.geoFilter='';collection.page=1;
const mangaThemeBase=renderTheme,mangaMarkerBase=renderMarkers,mangaOpenBase=openWine,mangaModeBase=setMode;
function mangaBadge(id){const n=MANGA_BY_ID[id];if(!n)return '';const labels=[...new Set(n.manga.map(x=>(x.series==='mariage'?'最终章':'原作')+'第'+x.volume+'卷'))];return `<span class="manga-badge" title="《神之水滴》 · ${labels.join('、')}（公开酒单记录）"><img class="manga-logo" src="labels/tdog.png" alt="神之水滴漫画标识" width="58" height="32" loading="lazy" decoding="async"></span>`}
function mangaEvidence(n){
 const m=MANGA_BY_ID[n.id];if(!m)return '';const grouped=new Map();for(const a of m.manga){const k=(a.series||'original')+':'+a.volume;if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(a)}
 return `<section class="manga-evidence"><h3>漫画登场记录 ${mangaBadge(n.id)}</h3><p class="smallnote">同款不同年份分别保留；未注明年份不等于 NV。以下为公开酒单对照记录，尚非漫画原页核验。</p>${[...grouped.values()].sort((a,b)=>a[0].volume-b[0].volume).map(aa=>`<div><b>${aa[0].series==='mariage'?'最终章':'原作'} · 第 ${aa[0].volume} 卷</b><span>${[...new Set(aa.map(a=>a.vintage||'年份未注明'))].join('、')}${aa.filter(a=>a.conflict).map(a=>'<br>⚠ '+escapeHTML(a.conflict)).join('')}</span><a href="${aa[0].source}" target="_blank" rel="noopener">酒单来源</a>${aa.find(a=>a.otherSource)?` · <a href="${aa.find(a=>a.otherSource).otherSource}" target="_blank" rel="noopener">日文对照</a>`:''}</div>`).join('')}${m.corrections?.length?`<details><summary>酒款与产地核对记录（${m.corrections.length}）</summary>${m.corrections.map(c=>`<p class="smallnote">${escapeHTML(c.note)} ${c.sources.map((src,i)=>`<a href="${src}" target="_blank" rel="noopener">来源${i+1}</a>`).join(' · ')}</p>`).join('')}</details>`:''}${m.geoSource?`<p class="smallnote"><a href="${m.geoSource}" target="_blank" rel="noopener">产地依据</a> · ${escapeHTML(m.geoPrecision||'示意点')}</p>`:''}<p class="smallnote">两份酒单可能引用共同资料，不能据此视为独立原作证据。漫画标识取自<a href="https://zh.wikipedia.org/wiki/File:Tdog.png" target="_blank" rel="noopener">维基百科 Tdog.png 文件页</a>，版权归原权利人。</p></section>`;
}
function mangaSupplement(n){const a=APOSTLES.find(a=>a.id===n.id);return `${a?`<section class="manga-apostle-note"><h3>《神之水滴》· 第 ${a.apostle} 使徒</h3><p>漫画对应年份：${escapeHTML(a.vintage)}</p><p>${escapeHTML(a.note||'')}</p></section>`:''}${mangaEvidence(n)}`}
const mangaWineBase=winePanel;winePanel=function(n){return mangaWineBase(n)+mangaSupplement(n)};
const mangaCardBase=card;card=function(n){return mangaCardBase(n).replace('</b>',mangaBadge(n.id)+'</b>')};
const mangaRenderBase=render;render=function(){mangaRenderBase();if(collection.mode==='map'&&MANGA_BY_ID[state.id])$('#title').insertAdjacentHTML('beforeend',mangaBadge(state.id))};
function mangaLabel(n){const img=WINE_IMAGES[n.id];if(!img||!['label','label-crop'].includes(img.kind))return '<p class="smallnote">纯酒标图片待补充；不以整瓶照片或其他酒款代替。</p>';return `<figure class="manga-label">${labelImage(img,n.en+"真实酒标")}<figcaption>${img.visibleVintage?'图示年份 '+img.visibleVintage:'图中未见年份 · 非 NV 判断'}<br>${escapeHTML(img.note||img.displayNote||'')} · <a href="${img.sourcePage}" target="_blank" rel="noopener">图片来源</a></figcaption></figure>`}
function mangaResults(){const query=collection.search.trim().toLowerCase();return MANGA_WINES.filter(n=>(!collection.series||n.manga.some(a=>a.series===collection.series))&&(!collection.volume||n.manga.some(a=>a.series+':'+a.volume===collection.volume))&&(!query||`${n.name} ${n.en} ${n.producer} ${n.place} ${(n.japaneseNames||[]).join(" ")} ${n.manga.map(a=>a.vintage||'').join(' ')}`.toLowerCase().includes(query))&&(!collection.geoFilter||`${n.lat},${n.lng}`===collection.geoFilter))}
function mangaTile(n){const ys=[...new Set(n.manga.map(a=>a.vintage||'年份未注明'))];return `<article class="manga-tile"><button class="manga-open" data-manga-wine="${n.id}"><b>${escapeHTML(n.name)} ${mangaBadge(n.id)}</b><span>${escapeHTML(n.producer)}</span><small>${escapeHTML(n.place||'产地待核验')}</small></button><div class="manga-years">漫画年份：${ys.join(' · ')}</div><small class="manga-status">${n.lat==null?'待定位':n.geoPrecision||'既有地图关联点'}${n.apostle?' · 第 '+n.apostle+' 使徒':''}</small></article>`}
function renderManga(){
 $('.tabs').hidden=true;$('.map-tools').hidden=true;$('#village-summary').hidden=true;$('#selected-label').hidden=true;
 $('#kind').textContent='DROPS OF GOD / 神之水滴';$('#title').textContent=collection.selected?catalog[collection.selected].name:'从漫画，走进葡萄酒地图。';$('#enname').textContent='Original 1–44 · Mariage 1–26';
 $('#summary').textContent='原作44卷＋最终章26卷。原作已对照两份公开酒单；最终章为单一酒单线索，均待原页核验。';
 $('#crumbs').innerHTML='<button data-mode="map">产区地图</button><span>／</span><button data-mode="manga">神之水滴</button>';
 $('#content').removeAttribute('aria-labelledby');
 if(collection.selected&&BY_ID[collection.selected]?.kind==='wine'){openWine(collection.selected);return}
 if(collection.selected){const n=catalog[collection.selected];$('#content').innerHTML=`<button class="plain" data-mode="manga">返回神之水滴</button><p class="wine-en">${escapeHTML(n.en)}</p><p>${escapeHTML(n.producer)}</p><p>${escapeHTML(n.place||'产地待核验')}</p>${mangaLabel(n)}${favoriteControls(n)}${statusHTML()}${mangaEvidence(n)}<p class="smallnote">定位精度：${escapeHTML(n.geoPrecision||'既有地图关联点')}。仅作产地学习示意，不代表酒庄或葡萄园的精确边界。</p>${n.placeId&&BY_ID[n.placeId]?`<button class="primary" data-place="${n.placeId}">深入关联产区</button>`:''}`;
 }else {const results=mangaResults(),pageSize=35,pages=Math.max(1,Math.ceil(results.length/pageSize));collection.page=Math.min(collection.page,pages);const page=results.slice((collection.page-1)*pageSize,collection.page*pageSize);
 $('#content').innerHTML=`<div class="stat-grid"><div><strong>${MANGA_STATS.uniqueWines}</strong><span>初步去重酒款</span></div><div><strong>${MANGA_STATS.mapped}</strong><span>已关联地图</span></div><div><strong>${MANGA_STATS.pendingLocations}</strong><span>待核验产地</span></div></div><p class="smallnote">来自 ${MANGA_STATS.sourceOccurrences} 条卷内酒单记录；已合并 ${MANGA_STATS.existingMatches} 款原有酒款。数量为当前工作索引，并非已核实的最终全量。原作 ${MANGA_STATS.originalUniqueWines} 款，最终章 ${MANGA_STATS.sequel.uniqueWines} 款，跨篇章同款合并。排除蒸馏酒与清酒。地图中包含待复核的产区示意点。</p><label class="manga-search">查找漫画酒款<input id="manga-search" type="search" value="${escapeHTML(collection.search)}" placeholder="酒款、生产者、产区或年份"></label><label class="manga-volume">按篇章筛选<select id="manga-series"><option value="">原作与最终章</option><option value="original" ${collection.series==='original'?'selected':''}>原作 · 44卷</option><option value="mariage" ${collection.series==='mariage'?'selected':''}>最终章 · 26卷</option></select></label><label class="manga-volume">按卷筛选<select id="manga-volume"><option value="">全部卷数</option>${[['original','原作',44],['mariage','最终章',26]].filter(([series])=>!collection.series||series===collection.series).map(([series,label,count])=>`<optgroup label="${label}">${Array.from({length:count},(_,i)=>`<option value="${series}:${i+1}" ${collection.volume===series+':'+(i+1)?'selected':''}>${label}第 ${i+1} 卷</option>`).join('')}</optgroup>`).join('')}</select></label>${collection.geoFilter?'<button class="plain" data-clear-geo>清除地图地点筛选</button>':''}<div class="section-head"><b>${results.length} 款酒</b><small>第 ${collection.page} / ${pages} 页</small></div>${page.map(mangaTile).join('')}${!results.length?'<p class="empty">没有符合条件的酒款。</p>':''}<div class="manga-pagination"><button data-manga-page="${collection.page-1}" ${collection.page<=1?'disabled':''}>上一页</button><button data-manga-page="${collection.page+1}" ${collection.page>=pages?'disabled':''}>下一页</button></div><p class="smallnote">参考酒单覆盖原作44卷与最终章26卷；不是漫画原页的完整审核，也不包括电视剧酒单。</p>`;
 }
 renderMarkers();syncBoxes();updateNav();
}
renderTheme=function(){if(collection.selected&&BY_ID[collection.selected]?.kind==='wine'){openWine(collection.selected);return}if(collection.mode==='manga')renderManga();else{mangaThemeBase();if(collection.mode==='apostles'){if(collection.selected){const n=catalog[collection.selected];$('#content').insertAdjacentHTML('beforeend',mangaEvidence(n));}document.querySelectorAll('.apostle-heading h2').forEach((el,i)=>{const n=collection.selected?catalog[collection.selected]:APOSTLES[i];el.insertAdjacentHTML('beforeend',mangaBadge(n.id))});}}};
renderMarkers=function(){if(collection.mode!=='manga'){mangaMarkerBase();return}markers.clearLayers();themeMarkers.clearLayers();const groups=new Map();const rows=collection.selected?[catalog[collection.selected]]:mangaResults();for(const n of rows){if(n.lat==null||n.lng==null)continue;const key=`${n.lat},${n.lng}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(n)}for(const [key,ns] of groups){const n=ns[0];L.marker([n.lat,n.lng],{icon:L.divIcon({className:'atlas-marker',html:`<button class="manga-map-pin" aria-label="${ns.length} 款漫画酒"><b>${ns.length}</b><span>${escapeHTML(ns.length===1?n.name:n.place||'漫画酒款')}</span></button>`,iconSize:[20,20],iconAnchor:[10,10]})}).on('click',()=>{if(ns.length===1)openWine(n.id);else{collection.geoFilter=key;collection.selected=null;collection.page=1;renderManga();$('aside').scrollTop=0}}).addTo(themeMarkers)}$('#level').textContent='神之水滴 / '+rows.filter(n=>n.lat!=null).length+' 款已定位';};
setMode=function(mode){if(mode!=='manga'){mangaModeBase(mode);return}collection.mode='manga';collection.selected=null;collection.geoFilter='';collection.page=1;updateNav();renderManga();$('aside').scrollTop=0;map.fitBounds([[-45,-125],[55,175]],{padding:[30,30],animate:false});try{history.replaceState(null,'','#manga')}catch(error){console.warn('URL update unavailable',error)}};
openWine=function(id,year){if(BY_ID[id]?.kind==='wine'){if(year)collection.years[id]=year;state.tab='earth';select(id);return}if(year)collection.years[id]=year;if(!MANGA_BY_ID[id]||catalog[id]?.apostle){mangaOpenBase(id,year);return}collection.mode='manga';collection.selected=id;const n=catalog[id];if(n.lat!=null)map.setView([n.lat,n.lng],11,{animate:false});renderManga();history.replaceState(null,'','#manga-'+id);$('aside').scrollTop=0};
document.addEventListener('input',e=>{if(e.target.id!=='manga-search')return;collection.search=e.target.value;collection.page=1;const pos=e.target.selectionStart;renderManga();const field=$('#manga-search');field.focus();field.setSelectionRange(pos,pos)});
document.addEventListener('change',e=>{if(e.target.id==='manga-series'){collection.series=e.target.value;collection.volume='';collection.page=1;renderManga()}if(e.target.id==='manga-volume'){collection.volume=e.target.value;collection.page=1;renderManga()}});
document.addEventListener('click',e=>{const w=e.target.closest('[data-manga-wine]');if(w)openWine(w.dataset.mangaWine);const p=e.target.closest('[data-manga-page]');if(p){collection.page=Number(p.dataset.mangaPage);renderManga();$('aside').scrollTop=0}if(e.target.closest('[data-clear-geo]')){collection.geoFilter='';renderManga()}});

function restoreWineRoute(hash){if(hash==='#manga'){setMode('manga');return}if(hash.startsWith('#manga-')){const id=hash.slice(7);if(catalog[id])openWine(id);return}if(hash.startsWith('#apostle-')){const n=APOSTLES.find(a=>String(a.apostle)===hash.slice(9));if(n)openWine(n.id)}}
window.addEventListener('hashchange',()=>restoreWineRoute(location.hash));
restoreWineRoute(initialWineRoute);

