'use strict';
state.mangaOnly=false;state.mangaPage=1;
const searchNormalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’'\-–—]/g,' ').replace(/\s+/g,' ').trim();
const wineSearchIndex=[...NODES.filter(n=>n.producer),...Object.values(catalog)].map(n=>({n,text:searchNormalize([n.name,n.en,typeof n.producer==='string'?n.producer:'',n.place,...(n.aliases||[]),...(BY_ID[n.producerId]?.aliases||[]),...(n.japaneseNames||[]),...(n.manga||[]).map(a=>a.vintage||'')].join(' '))}));
function searchWines(query){const words=searchNormalize(query).split(' ').filter(Boolean);return words.length?wineSearchIndex.filter(x=>words.every(w=>x.text.includes(w))).map(x=>x.n):[]}
function updateWineSearch(){const q=$('#wine-search').value.trim(),box=$('#wine-search-results');if(!q){box.hidden=true;return}const rows=searchWines(q);box.hidden=false;box.innerHTML=`<p role="status">${rows.length} 个匹配${rows.length>18?' · 显示前 18 款，请增加关键词':''}</p>${rows.slice(0,18).map(n=>`<button type="button" data-search-wine="${n.id}"><b>${escapeHTML(n.name)} ${mangaBadge(n.id)}</b><small>${escapeHTML(n.en)} · ${escapeHTML(n.producer===true?'酒庄 / 生产者':n.producer||'')}</small></button>`).join('')}${!rows.length?'<p>没有找到酒款，请尝试中文名、原文名或酒庄名。</p>':''}`}
$('#wine-search').addEventListener('input',updateWineSearch);$('#wine-search').addEventListener('focus',()=>{if($('#wine-search').value)updateWineSearch()});
$('.wine-search-nav').addEventListener('submit',e=>{e.preventDefault();const first=$('#wine-search-results [data-search-wine]');if(first)first.click()});
$('#wine-search').addEventListener('keydown',e=>{if(e.key==='Escape')$('#wine-search-results').hidden=true;if(e.key==='ArrowDown'){$('#wine-search-results button')?.focus();e.preventDefault()}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-search-wine]');if(b){$('#wine-search-results').hidden=true;if(!MANGA_BY_ID[b.dataset.searchWine])state.mangaOnly=false;if(BY_ID[b.dataset.searchWine]?.producer){state.mangaOnly=false;collection.mode='map';select(b.dataset.searchWine);}else openWine(b.dataset.searchWine);syncMangaFilter()}else if(!e.target.closest('.wine-search-nav'))$('#wine-search-results').hidden=true});
function mangaAtPlace(n){return MANGA_WINES.filter(w=>{const wine=BY_ID[w.id];if(n.kind==='wine')return w.id===n.id;if(n.producer)return wine?.producerId===n.id;if(wine&&(ancestors(wine).some(a=>a.id===n.id)||wine.appellationId&&ancestors(BY_ID[wine.appellationId]).some(a=>a.id===n.id)))return true;if(wine)return false;const p=BY_ID[w.placeId];if(p&&(p.id===n.id||ancestors(p).some(a=>a.id===n.id)))return true;if(n.id==='france')return /法国|France|フランス/i.test(w.place||'');const name=searchNormalize(n.en);return name.length>4&&searchNormalize(w.place).includes(name)})}
const mangaPlaceIndex=new Map(NODES.map(n=>[n.id,mangaAtPlace(n)]));
const geographicFrontier=frontier;frontier=function(id,z){const rows=geographicFrontier(id,z);return state.mangaOnly?rows.filter(n=>mangaPlaceIndex.get(n.id)?.length):rows};
function syncMangaFilter(){const input=$('#manga-map-filter');input.checked=state.mangaOnly;input.closest('label').hidden=collection.mode==='favorites';}
function mangaPlacePanel(n){const rows=mangaPlaceIndex.get(n.id)||[];const next=[...new Map([...children(n.id).filter(x=>x.kind!=='wine'),...rows.filter(w=>BY_ID[w.id]?.appellationId===n.id).map(w=>BY_ID[BY_ID[w.id]?.producerId]).filter(Boolean)].filter(x=>mangaPlaceIndex.get(x.id)?.length).map(x=>[x.id,x])).values()];return `<section class="manga-place-results"><div class="section-head"><h2>神之水滴</h2><small>${rows.length} 款 · ${escapeHTML(n.name)}</small></div><p class="smallnote">仅显示与当前产地有关的漫画酒款。产地未确认的酒款可通过顶部搜索查找。</p>${next.length?`<h3>继续探索产地与酒庄</h3>${next.map(card).join('')}`:''}<h3>当前产地的漫画酒款</h3>${rows.length?rows.slice((state.mangaPage-1)*30,state.mangaPage*30).map(mangaTile).join(''):'<p class="empty">当前产地暂无已关联的漫画酒款。</p>'}${rows.length>30?`<div class="manga-pagination"><button data-place-page="${state.mangaPage-1}" ${state.mangaPage===1?'disabled':''}>上一页</button><span>${state.mangaPage} / ${Math.ceil(rows.length/30)}</span><button data-place-page="${state.mangaPage+1}" ${state.mangaPage*30>=rows.length?'disabled':''}>下一页</button></div>`:''}</section>`}
const placeRender=render;render=function(){placeRender();syncMangaFilter();if(collection.mode!=='map'||!state.mangaOnly)return;const n=BY_ID[state.id];if(!n.producer&&n.kind!=='wine'){$('#content').innerHTML=mangaPlacePanel(n);$('#content').removeAttribute('aria-labelledby');$('.tabs').hidden=true;}else if(n.producer){document.querySelectorAll('.estate-wine-index .location[data-place]').forEach(b=>{if(!MANGA_BY_ID[b.dataset.place])b.hidden=true});}$('#village-summary').hidden=true;};
const placeMarkers=renderMarkers;renderMarkers=function(){placeMarkers();syncMangaFilter();if(collection.mode!=='map'||!state.mangaOnly)return;$('#village-summary').hidden=true;const rows=mangaPlaceIndex.get(state.id)||[],groups=new Map();for(const w of rows){if(BY_ID[w.id]||w.lat==null||w.lng==null)continue;const k=w.lat+','+w.lng;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(w)}for(const ws of groups.values()){const n=ws[0];L.marker([n.lat,n.lng],{icon:L.divIcon({className:'atlas-marker',html:`<button class="manga-map-pin"><b>${ws.length}</b><span>${escapeHTML(ws.length===1?n.name:n.place||'神之水滴')}</span></button>`,iconSize:[20,20],iconAnchor:[10,10]})}).on('click',()=>{if(ws.length===1)openWine(n.id);else{$('#content').innerHTML=`<button class="text-button" data-place="${state.id}">返回当前产地</button><h2>神之水滴 · 此处 ${ws.length} 款</h2>${ws.map(mangaTile).join('')}`}}).addTo(themeMarkers)}$('#level').textContent='神之水滴 · '+rows.length+' 款关联当前产地';};
$('#manga-map-filter').addEventListener('change',e=>{state.mangaOnly=e.target.checked;state.mangaPage=1;if(collection.mode!=='map'){collection.mode='map';collection.selected=null;}render();updateNav();});
const geographicMode=setMode;setMode=function(mode){if(mode==='manga'||mode==='apostles'){state.mangaOnly=true;collection.mode='map';collection.selected=null;select(state.id);return}geographicMode(mode);syncMangaFilter()};
if(collection.mode==='manga'&&!collection.selected||collection.mode==='apostles'&&!collection.selected)setMode('manga');else if(collection.mode==='map')render();

const searchPlaceSelect=select;select=function(id){state.mangaPage=1;searchPlaceSelect(id)};
document.addEventListener('click',e=>{const b=e.target.closest('[data-place-page]');if(b){state.mangaPage=Number(b.dataset.placePage);render();$('aside').scrollTop=0}});
